##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.90-avail/%M%
#   Revision:		%I%
#   First Edition:	2017/05/17
#   Last Mod.:		%U%, %G%
#
#   Authors:		Xavier Delaruelle, xavier.delaruelle@cea.fr
#
#   Description:	Testuite testsequence
#   Command:		avail
#   Modulefiles:
#   Sub-Command:
#
#   Comment:	%C{
#			Check the module 'avail' command on all existing modulefiles
#			with specific terminal width setup
#		}C%
#
##############################################################################

#
#  Check this only for the /bin/sh
#

set test_cols 201
if {![info exists term_cols]} {
    # skip tests if current terminal width is unknown
    send_user "\tskipping terminal width-specific tests\n"
# set a specific terminal width
} elseif {[catch {exec stty cols $test_cols}] || [getTtyCols] ne $test_cols} {
    send_user "\tskipping terminal width-specific tests, cannot set width\n"
} else {

# ensure avail tests are made using in depth mode
setenv_var MODULES_AVAIL_INDEPTH 1

set test_cols_small 25
set test_cols_othos 120

set ts_key "Key:
(@)=module-alias  (symbolic-version)  "
set ts_key_small "Key:
(@)=module-alias           
(symbolic-version)  "

set len  [string length $modpath]
set lrep [expr {($test_cols - $len - 2)/2}]
set rrep [expr {$test_cols - $len - 2 - $lrep}]
set ts_sh "[string repeat {-} $lrep] $modpath [string repeat {-} $rrep]
alias/1.0           info/shells                    loc_sym/alias3                                                       modbad/paths         spread/4.0                                       
alias/2.0           info/shellsexp                 loc_sym/alias4                                                       modbad/prepend-path  spread/5.0                                       
alias/3.0           info/specified(foo)            loc_sym/alias5                                                       modbad/remove-path   spread/6.0                                       
append/0.1          info/type                      loc_sym/alias6                                                       modbad/sh-to-mod     spread/7.0                                       
append/0.2          info/user                      loc_sym/alias7                                                       module/2.0           spread/8.0                                       
append/0.3          info/userexp                   loc_sym/alias8                                                       module/bad           spreadrc/dir1/1.0                                
append/0.4          inforc/1.0                     loc_sym/alias9                                                       module/empty         spreadrc/dir2/1.0                                
append/0.5          inforc/2.0(avail:bar:default)  loc_sym/alias10                                                      module/err           spreadrc/dir3/1.0                                
append/1.0          inforc/foo(@)                  loc_sym/alias11                                                      module/lbad          spreadrc/dir4/1.0                                
append/1.1          load/00                        loc_sym/exec1                                                        module/lerr          spreadrc/dir5/1.0                                
append/1.3          load/10                        loc_sym/exec2                                                        module/lunk          spreadrc/dir6/1.0                                
append/1.4          load/11                        loc_sym/exec3                                                        module/meta          spreadrc/dir7/1.0                                
append/1.5          load/12                        loc_sym/getvers1                                                     module/relpath       spreadrc/dir8/1.0                                
append/1.6          load/13                        loc_sym/getvers2                                                     module/unk           symlink/0.9                                      
append/1.7          load/14                        loc_sym/getvers3                                                     modvar/modfile       symlink/1(@)                                     
append/1.8          load/15                        loc_sym/getvers4                                                     modvar/submodfile    symlink/1.2(default:new)                         
append/2.0          load/16                        loc_sym/getvers5                                                     prepend/0.1          symlink/bar(@)                                   
append/2.1          load/17                        loc_sym/getvers6                                                     prepend/0.2          symlink2/1.0                                     
append/2.2          load/18                        loc_sym/getvers7                                                     prepend/0.3          symlink2/2.0                                     
append/2.3          load/19                        loc_sym/getvers8                                                     prepend/0.4          system/1.0                                       
append/2.4          load/20                        loc_sym/getvers9                                                     prepend/0.5          system/2.0                                       
append/4.0          load/21                        loc_sym/getvers10                                                    prepend/1.0          test/1.0                                         
append/4.1          load/22                        loc_sym/versinf1                                                     prepend/1.1          test/1.2                                         
append/5.0          load/23                        loc_sym/versinf2                                                     prepend/1.3          test/2.0                                         
append/6.0          load/24                        loc_sym/versinf3                                                     prepend/1.4          tr2_loc/(trreg)                                  
append/7.0          load/25                        loc_sym/versinf4                                                     prepend/1.5          tr2_loc/al1(tr2unstable:@)                       
append/8.0          load/26                        loc_sym/versinf5                                                     prepend/1.6          tr2_loc/al2(tr2bar:@)                            
averssort/1(@)      load/27                        loc_sym/versinf6                                                     prepend/1.7          tr2_loc/al3(default:tr2exp:trreg:@)              
averssort/1.2.4(@)  load/28                        loc_sym/versinf7                                                     prepend/1.8          tr2_loc/al4(@)                                   
averssort/1.10(@)   load/29                        loc_sym/version1                                                     prepend/1.9          tr2_loc/al5(default:trreg:@)                     
bad/after(good)     load/30                        loc_sym/version2                                                     prepend/1.10         tr_loc/al1(tr2unstable:trunstable:@)             
bad/before          load/all(default)              loc_sym/version3                                                     prepend/2.0          tr_loc/al2(default:tr2bar:tr2exp:trbar:trreg:@)  
bad2/body           loc_def/default                loc_sym/version4                                                     prepend/2.1          tr_loc/al3(trexp:@)                              
bad2/proc           loc_def/truedef                loc_sym/version5                                                     prepend/2.2          tr_loc/al4(@)                                    
break/1.0           loc_dv1/1.0                    loc_sym/version6                                                     prepend/2.3          tr_loc/al5(@)                                    
break/2.0           loc_dv1/2.0                    loc_sym/version7                                                     prepend/2.4          trace/all_off                                    
break/3.0           loc_dv2/1.0(default)           loc_sym/version8                                                     prepend/3.0          trace/all_on                                     
break/4.0           loc_dv2/2.0                    loc_sym/version9                                                     prepend/3.1          uname/cache                                      
break/5.0           loc_dv3/1.0                    loc_sym/version10                                                    prepend/4.0          uname/domain                                     
break/6.0           loc_dv3/2.0                    loc_sym/version11                                                    prepend/8.0          uname/machine                                    
chdir/1.0           loc_dv4/1.0                    loc_sym/version12                                                    prereq/full          uname/nodename                                   
chdir/2.0           loc_dv6/1.0                    loc_sym/version13                                                    prereq/fullpath      uname/release                                    
chdir/3.0           loc_dv6/2.0/1.0                loc_sym/version14                                                    prereq/module        uname/sysname                                    
chdir/4.0           loc_dv7/1.0                    loc_sym/version15                                                    prereq/orlist        uname/unk                                        
coll/a              loc_dv7/2.0/(default)          loc_sym/version16                                                    prereq/relpath       uname/version                                    
coll/b              loc_dv7/2.0/1.0                loc_sym/version17                                                    puts/1               unsetenv/0.6                                     
coll/c              loc_dv7/3.0                    loc_sym/version18                                                    puts/2               unsetenv/0.8                                     
coll/d              loc_dv8/1.0                    loc_sym/version19                                                    puts/3               unsetenv/0.9                                     
conflict/full       loc_dv8/2.0                    loc_sym/version20                                                    puts/4               unsetenv/1.0                                     
conflict/fullpath   loc_dv9/1.0(default)           loc_sym/version21                                                    puts/5               use/1.0(default)                                 
conflict/module     loc_dv9/2.0                    loc_sym/version22                                                    puts/6               use/2.0                                          
conflict/relpath    loc_dvv1/1.0(default)          loc_sym/version23                                                    puts/7               use/2.1                                          
continue/1.0        loc_dvv1/2.0                   loc_sym/version24                                                    puts/8               use/2.2                                          
continue/2.0        loc_fq/1.0                     loc_sym/version25                                                    puts/9               use/3.0                                          
continue/3.0        loc_rc1/1.0(foo)               loc_sym/version26                                                    recurs/modA          use/3.1                                          
continue/4.0        loc_rc1/2.0                    loc_tr/(reg)                                                         recurs/modB          use/3.2                                          
continue/5.0        loc_rc2/1.0(bar:blah:foo)      loc_tr/1.0(cur:stable)                                               remove/0.3           use/4.0                                          
continue/6.0        loc_rc2/2.0                    loc_tr/2.0(next:tr2unstable:trunstable:unstable)                     remove/0.4           use/4.1                                          
dirmodalias(@)      loc_rc3/1.0(default)           loc_tr/3.0(bar:default:exp:foo:reg:tr2bar:tr2exp:trbar:trexp:trreg)  remove/0.5           user/adv                                         
dirmodalias/1.0     loc_rc3/2.0(cur:stable)        loc_tr/al1(unstable:@)                                               remove/1.0           user/advanced                                    
dirmodvirt          loc_rc3/3.0(chk:exp:new:test)  loc_tr/al2(bar:default:exp:reg:trexp:@)                              remove/1.3           user/exp                                         
dirmodvirt/1.0      loc_rc4/1.0                    loc_tr/al3(default:exp:reg:@)                                        remove/1.4           user/expert                                      
empty/1.0           loc_rc4/2.0(default)           loc_tr/al4(default:reg:@)                                            remove/1.5           user/nov                                         
eschars/1.0         loc_rc4/3.0                    loc_virt1/1.0                                                        remove/1.6           user/novice                                      
exit/1.0            loc_rc5/1.0                    loc_virt1/2.0                                                        remove/1.7           user/undef                                       
exit/2.0            loc_rc5/2.0                    loc_virt1/3.0                                                        remove/1.8           verbose/msg                                      
exit/3.0            loc_rc6/0.9                    loc_virt1/4.0                                                        remove/2.0           verbose/off                                      
exit/4.0            loc_rc6/1(@)                   loc_virt2/1.0                                                        remove/2.3           verbose/on                                       
function/1.0        loc_rc6/1.2(default:new)       loc_virt2/2.0                                                        remove/2.4           verbose/undef                                    
function/2.0        loc_rc6/bar(@)                 log/badfac                                                           remove/3.0           versions/1.1                                     
getenv/0.6          loc_rc7/0.9                    log/err_both_1                                                       remove/3.1           versions/1.2                                     
getenv/1.0          loc_rc7/1(@)                   log/err_both_2                                                       remove/4.0           versions/1.3                                     
help/2.0            loc_rc7/1.2                    log/err_file                                                         remove/4.1           verssort/1                                       
info/command        loc_rc7/bar(@)                 log/err_syslog                                                       remove/4.2           verssort/1.2.1                                   
info/commandexp     loc_rc8/0.9(@)                 modbad/append-path                                                   remove/5.0           verssort/1.2.4                                   
info/isavail        loc_rc8/1.0                    modbad/autoinit                                                      remove/8.0           verssort/1.8-2015-12-01                          
info/isloaded       loc_rc010/2.0                  modbad/clear                                                         setenv/0.6           verssort/1.8-2016-02-01                          
info/issaved        loc_rcv1/1(@)                  modbad/config                                                        setenv/0.7.1         verssort/1.10                                    
info/isused         loc_rcv1/1.1                   modbad/edit                                                          setenv/0.7.2         whatis/lines                                     
info/loaded         loc_rcv1/1.2(default:new)      modbad/empty                                                         setenv/0.8           whatis/multiple                                  
info/mode1          loc_rcv1/2.0                   modbad/foo                                                           setenv/1.0           whatis/none                                      
info/mode2          loc_rcv1/bar(@)                modbad/help                                                          source/0.9           whatis/single                                    
info/mode3          loc_rcv2/1.2                   modbad/info-loaded                                                   source/1.0           whatis/string                                    
info/mode4          loc_rcv2/1.5                   modbad/is-avail                                                      source/1.1           x-resource/1                                     
info/mode5          loc_rcv2/2.0                   modbad/is-loaded                                                     source/1.2           
info/mode6          loc_sym/1.0                    modbad/is-saved                                                      spread/1.0           
info/name           loc_sym/alias1                 modbad/is-used                                                       spread/2.0           
info/others         loc_sym/alias2                 modbad/path                                                          spread/3.0           "

set ts_sh_json "{\"$modpath\": {
\"loc_tr/al1\": { \"name\": \"loc_tr/al1\", \"type\": \"alias\", \"symbols\": \[ \"unstable\" \], \"tags\": \[\], \"target\": \"loc_tr/next\", \"via\": \"\"},
\"remove/5.0\": { \"name\": \"remove/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/5.0\", \"via\": \"\"},
\"symlink2/2.0\": { \"name\": \"symlink2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink2/2.0\", \"via\": \"\"},
\"loc_def/default\": { \"name\": \"loc_def/default\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_def/default\", \"via\": \"\"},
\"loc_tr/al2\": { \"name\": \"loc_tr/al2\", \"type\": \"alias\", \"symbols\": \[ \"bar\", \"default\", \"exp\", \"reg\", \"trexp\" \], \"tags\": \[\], \"target\": \"loc_tr/foo\", \"via\": \"\"},
\"verssort/1.8-2015-12-01\": { \"name\": \"verssort/1.8-2015-12-01\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.8-2015-12-01\", \"via\": \"\"},
\"whatis/single\": { \"name\": \"whatis/single\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/single\", \"via\": \"\"},
\"loc_virt2/1.0\": { \"name\": \"loc_virt2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt2/2.0\", \"via\": \"\"},
\"loc_tr/al3\": { \"name\": \"loc_tr/al3\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"exp\", \"reg\" \], \"tags\": \[\], \"target\": \"loc_tr/al2\", \"via\": \"\"},
\"uname/machine\": { \"name\": \"uname/machine\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/machine\", \"via\": \"\"},
\"loc_virt1/3.0\": { \"name\": \"loc_virt1/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_virt\", \"via\": \"\"},
\"loc_tr/al4\": { \"name\": \"loc_tr/al4\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"reg\" \], \"tags\": \[\], \"target\": \"loc_tr/exp\", \"via\": \"\"},
\"loc_dv6/1.0\": { \"name\": \"loc_dv6/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv6/1.0\", \"via\": \"\"},
\"function/1.0\": { \"name\": \"function/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/function/1.0\", \"via\": \"\"},
\"loc_rc5/1.0\": { \"name\": \"loc_rc5/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc5/1.0\", \"via\": \"\"},
\"whatis/string\": { \"name\": \"whatis/string\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/string\", \"via\": \"\"},
\"loc_rc4/3.0\": { \"name\": \"loc_rc4/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/3.0\", \"via\": \"\"},
\"loc_rcv1/2.0\": { \"name\": \"loc_rcv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"continue/6.0\": { \"name\": \"continue/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/6.0\", \"via\": \"\"},
\"alias/1.0\": { \"name\": \"alias/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/1.0\", \"via\": \"\"},
\"setenv/0.6\": { \"name\": \"setenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.6\", \"via\": \"\"},
\"append/5.0\": { \"name\": \"append/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/5.0\", \"via\": \"\"},
\"setenv/0.8\": { \"name\": \"setenv/0.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.8\", \"via\": \"\"},
\"use/2.0\": { \"name\": \"use/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.0\", \"via\": \"\"},
\"use/2.1\": { \"name\": \"use/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.1\", \"via\": \"\"},
\"remove/2.0\": { \"name\": \"remove/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.0\", \"via\": \"\"},
\"unsetenv/1.0\": { \"name\": \"unsetenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/1.0\", \"via\": \"\"},
\"use/2.2\": { \"name\": \"use/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.2\", \"via\": \"\"},
\"verssort/1.10\": { \"name\": \"verssort/1.10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.10\", \"via\": \"\"},
\"user/undef\": { \"name\": \"user/undef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/undef\", \"via\": \"\"},
\"bad/after\": { \"name\": \"bad/after\", \"type\": \"modulefile\", \"symbols\": \[ \"good\" \], \"tags\": \[\], \"pathname\": \"$modpath/bad/after\", \"via\": \"\"},
\"remove/2.3\": { \"name\": \"remove/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.3\", \"via\": \"\"},
\"remove/2.4\": { \"name\": \"remove/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.4\", \"via\": \"\"},
\"info/user\": { \"name\": \"info/user\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/user\", \"via\": \"\"},
\"exit/4.0\": { \"name\": \"exit/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/4.0\", \"via\": \"\"},
\"modbad/autoinit\": { \"name\": \"modbad/autoinit\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/autoinit\", \"via\": \"\"},
\"loc_rc3/2.0\": { \"name\": \"loc_rc3/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"cur\", \"stable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/2.0\", \"via\": \"\"},
\"puts/1\": { \"name\": \"puts/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/1\", \"via\": \"\"},
\"puts/2\": { \"name\": \"puts/2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/2\", \"via\": \"\"},
\"uname/domain\": { \"name\": \"uname/domain\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/domain\", \"via\": \"\"},
\"uname/sysname\": { \"name\": \"uname/sysname\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/sysname\", \"via\": \"\"},
\"continue/3.0\": { \"name\": \"continue/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/3.0\", \"via\": \"\"},
\"puts/3\": { \"name\": \"puts/3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/3\", \"via\": \"\"},
\"puts/4\": { \"name\": \"puts/4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/4\", \"via\": \"\"},
\"append/2.0\": { \"name\": \"append/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.0\", \"via\": \"\"},
\"puts/5\": { \"name\": \"puts/5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/5\", \"via\": \"\"},
\"modbad/append-path\": { \"name\": \"modbad/append-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/append-path\", \"via\": \"\"},
\"append/2.1\": { \"name\": \"append/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.1\", \"via\": \"\"},
\"loc_rcv1/1\": { \"name\": \"loc_rcv1/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rcv1/1.2\", \"via\": \"\"},
\"append/2.2\": { \"name\": \"append/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.2\", \"via\": \"\"},
\"puts/6\": { \"name\": \"puts/6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/6\", \"via\": \"\"},
\"append/2.3\": { \"name\": \"append/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.3\", \"via\": \"\"},
\"puts/7\": { \"name\": \"puts/7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/7\", \"via\": \"\"},
\"modbad/path\": { \"name\": \"modbad/path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/path\", \"via\": \"\"},
\"append/2.4\": { \"name\": \"append/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.4\", \"via\": \"\"},
\"puts/8\": { \"name\": \"puts/8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/8\", \"via\": \"\"},
\"puts/9\": { \"name\": \"puts/9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/9\", \"via\": \"\"},
\"user/advanced\": { \"name\": \"user/advanced\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/advanced\", \"via\": \"\"},
\"uname/release\": { \"name\": \"uname/release\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/release\", \"via\": \"\"},
\"spreadrc/dir8/1.0\": { \"name\": \"spreadrc/dir8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir8/1.0\", \"via\": \"\"},
\"exit/1.0\": { \"name\": \"exit/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/1.0\", \"via\": \"\"},
\"loc_dv3/1.0\": { \"name\": \"loc_dv3/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv3/1.0\", \"via\": \"\"},
\"loc_rc2/1.0\": { \"name\": \"loc_rc2/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"bar\", \"blah\", \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc2/1.0\", \"via\": \"\"},
\"modbad/config\": { \"name\": \"modbad/config\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/config\", \"via\": \"\"},
\"module/bad\": { \"name\": \"module/bad\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/bad\", \"via\": \"\"},
\"prereq/fullpath\": { \"name\": \"prereq/fullpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/fullpath\", \"via\": \"\"},
\"loc_sym/getvers1\": { \"name\": \"loc_sym/getvers1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers1\", \"via\": \"\"},
\"verbose/undef\": { \"name\": \"verbose/undef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/undef\", \"via\": \"\"},
\"loc_sym/getvers2\": { \"name\": \"loc_sym/getvers2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers2\", \"via\": \"\"},
\"loc_sym/getvers3\": { \"name\": \"loc_sym/getvers3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers3\", \"via\": \"\"},
\"loc_sym/getvers4\": { \"name\": \"loc_sym/getvers4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers4\", \"via\": \"\"},
\"loc_sym/getvers5\": { \"name\": \"loc_sym/getvers5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers5\", \"via\": \"\"},
\"modbad/is-saved\": { \"name\": \"modbad/is-saved\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-saved\", \"via\": \"\"},
\"modbad/foo\": { \"name\": \"modbad/foo\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/foo\", \"via\": \"\"},
\"modvar/submodfile\": { \"name\": \"modvar/submodfile\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modvar/submodfile\", \"via\": \"\"},
\"spread/7.0\": { \"name\": \"spread/7.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/7.0\", \"via\": \"\"},
\"loc_sym/getvers6\": { \"name\": \"loc_sym/getvers6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers6\", \"via\": \"\"},
\"modbad/is-avail\": { \"name\": \"modbad/is-avail\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-avail\", \"via\": \"\"},
\"loc_sym/getvers7\": { \"name\": \"loc_sym/getvers7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers7\", \"via\": \"\"},
\"loc_sym/getvers8\": { \"name\": \"loc_sym/getvers8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers8\", \"via\": \"\"},
\"loc_sym/getvers9\": { \"name\": \"loc_sym/getvers9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers9\", \"via\": \"\"},
\"loc_dv1/2.0\": { \"name\": \"loc_dv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv1/2.0\", \"via\": \"\"},
\"info/isloaded\": { \"name\": \"info/isloaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isloaded\", \"via\": \"\"},
\"dirmodalias\": { \"name\": \"dirmodalias\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6\", \"via\": \"\"},
\"dirmodvirt/1.0\": { \"name\": \"dirmodvirt/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"loc_rc6/bar\": { \"name\": \"loc_rc6/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6/1.2\", \"via\": \"\"},
\"prepend/4.0\": { \"name\": \"prepend/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/4.0\", \"via\": \"\"},
\"loc_dv9/2.0\": { \"name\": \"loc_dv9/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv9/2.0\", \"via\": \"\"},
\"load/all\": { \"name\": \"load/all\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/load/all\", \"via\": \"\"},
\"spread/4.0\": { \"name\": \"spread/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/4.0\", \"via\": \"\"},
\"chdir/3.0\": { \"name\": \"chdir/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/3.0\", \"via\": \"\"},
\"loc_dv7/2.0/1.0\": { \"name\": \"loc_dv7/2.0/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/2.0/1.0\", \"via\": \"\"},
\"info/shellsexp\": { \"name\": \"info/shellsexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/shellsexp\", \"via\": \"\"},
\"spreadrc/dir5/1.0\": { \"name\": \"spreadrc/dir5/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir5/1.0\", \"via\": \"\"},
\"inforc/1.0\": { \"name\": \"inforc/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/inforc/1.0\", \"via\": \"\"},
\"test/2.0\": { \"name\": \"test/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/2.0\", \"via\": \"\"},
\"info/others\": { \"name\": \"info/others\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/others\", \"via\": \"\"},
\"loc_tr/3.0\": { \"name\": \"loc_tr/3.0\", \"type\": \"modulefile\", \"symbols\": \[ \"bar\", \"default\", \"exp\", \"foo\", \"reg\", \"tr2bar\", \"tr2exp\", \"trbar\", \"trexp\", \"trreg\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/3.0\", \"via\": \"\"},
\"prepend/1.0\": { \"name\": \"prepend/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.0\", \"via\": \"\"},
\"loc_rcv1/bar\": { \"name\": \"loc_rcv1/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rcv1/1.2\", \"via\": \"\"},
\"spread/1.0\": { \"name\": \"spread/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/1.0\", \"via\": \"\"},
\"prepend/1.1\": { \"name\": \"prepend/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.1\", \"via\": \"\"},
\"loc_dv8/1.0\": { \"name\": \"loc_dv8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv8/1.0\", \"via\": \"\"},
\"loc_dv7/3.0\": { \"name\": \"loc_dv7/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/3.0\", \"via\": \"\"},
\"break/4.0\": { \"name\": \"break/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/4.0\", \"via\": \"\"},
\"symlink/1.2\": { \"name\": \"symlink/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/symlink/1.2\", \"via\": \"\"},
\"symlink/1\": { \"name\": \"symlink/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"symlink/1.2\", \"via\": \"\"},
\"prepend/1.3\": { \"name\": \"prepend/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.3\", \"via\": \"\"},
\"prepend/1.4\": { \"name\": \"prepend/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.4\", \"via\": \"\"},
\"averssort/1\": { \"name\": \"averssort/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1\", \"via\": \"\"},
\"prepend/1.5\": { \"name\": \"prepend/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.5\", \"via\": \"\"},
\"trace/all_off\": { \"name\": \"trace/all_off\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/trace/all_off\", \"via\": \"\"},
\"loc_rc7/1.2\": { \"name\": \"loc_rc7/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc7/1.2\", \"via\": \"\"},
\"bad/before\": { \"name\": \"bad/before\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad/before\", \"via\": \"\"},
\"prepend/1.6\": { \"name\": \"prepend/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.6\", \"via\": \"\"},
\"whatis/lines\": { \"name\": \"whatis/lines\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/lines\", \"via\": \"\"},
\"prepend/1.7\": { \"name\": \"prepend/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.7\", \"via\": \"\"},
\"prepend/1.8\": { \"name\": \"prepend/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.8\", \"via\": \"\"},
\"loc_sym/version1\": { \"name\": \"loc_sym/version1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version1\", \"via\": \"\"},
\"uname/nodename\": { \"name\": \"uname/nodename\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/nodename\", \"via\": \"\"},
\"loc_dvv1/2.0\": { \"name\": \"loc_dvv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dvv1/.common\", \"via\": \"\"},
\"prepend/1.9\": { \"name\": \"prepend/1.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.9\", \"via\": \"\"},
\"loc_sym/version2\": { \"name\": \"loc_sym/version2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version2\", \"via\": \"\"},
\"prereq/relpath\": { \"name\": \"prereq/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/relpath\", \"via\": \"\"},
\"loc_sym/version3\": { \"name\": \"loc_sym/version3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version3\", \"via\": \"\"},
\"loc_sym/version4\": { \"name\": \"loc_sym/version4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version4\", \"via\": \"\"},
\"loc_sym/version5\": { \"name\": \"loc_sym/version5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version5\", \"via\": \"\"},
\"verssort/1.8-2016-02-01\": { \"name\": \"verssort/1.8-2016-02-01\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.8-2016-02-01\", \"via\": \"\"},
\"loc_sym/version6\": { \"name\": \"loc_sym/version6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version6\", \"via\": \"\"},
\"loc_sym/version7\": { \"name\": \"loc_sym/version7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version7\", \"via\": \"\"},
\"setenv/1.0\": { \"name\": \"setenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/1.0\", \"via\": \"\"},
\"break/1.0\": { \"name\": \"break/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/1.0\", \"via\": \"\"},
\"loc_virt2/2.0\": { \"name\": \"loc_virt2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt2/2.0\", \"via\": \"\"},
\"loc_sym/version8\": { \"name\": \"loc_sym/version8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version8\", \"via\": \"\"},
\"loc_virt1/4.0\": { \"name\": \"loc_virt1/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_virt\", \"via\": \"\"},
\"conflict/full\": { \"name\": \"conflict/full\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/full\", \"via\": \"\"},
\"prereq/module\": { \"name\": \"prereq/module\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/module\", \"via\": \"\"},
\"loc_sym/version9\": { \"name\": \"loc_sym/version9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version9\", \"via\": \"\"},
\"function/2.0\": { \"name\": \"function/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/function/2.0\", \"via\": \"\"},
\"user/expert\": { \"name\": \"user/expert\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/expert\", \"via\": \"\"},
\"loc_rc5/2.0\": { \"name\": \"loc_rc5/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc5/2.0\", \"via\": \"\"},
\"eschars/1.0\": { \"name\": \"eschars/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/eschars/1.0\", \"via\": \"\"},
\"modbad/help\": { \"name\": \"modbad/help\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/help\", \"via\": \"\"},
\"source/0.9\": { \"name\": \"source/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/0.9\", \"via\": \"\"},
\"loc_rc6/1\": { \"name\": \"loc_rc6/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6/1.2\", \"via\": \"\"},
\"averssort/1.10\": { \"name\": \"averssort/1.10\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1.10\", \"via\": \"\"},
\"verssort/1\": { \"name\": \"verssort/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1\", \"via\": \"\"},
\"module/lbad\": { \"name\": \"module/lbad\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lbad\", \"via\": \"\"},
\"alias/2.0\": { \"name\": \"alias/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/2.0\", \"via\": \"\"},
\"loc_rcv2/1.2\": { \"name\": \"loc_rcv2/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv2/.common\", \"via\": \"\"},
\"spreadrc/dir2/1.0\": { \"name\": \"spreadrc/dir2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir2/1.0\", \"via\": \"\"},
\"append/6.0\": { \"name\": \"append/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/6.0\", \"via\": \"\"},
\"info/loaded\": { \"name\": \"info/loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/loaded\", \"via\": \"\"},
\"loc_rcv2/1.5\": { \"name\": \"loc_rcv2/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_rcv\", \"via\": \"\"},
\"use/3.0\": { \"name\": \"use/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.0\", \"via\": \"\"},
\"remove/3.0\": { \"name\": \"remove/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/3.0\", \"via\": \"\"},
\"loc_rc6/0.9\": { \"name\": \"loc_rc6/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc6/0.9\", \"via\": \"\"},
\"use/3.1\": { \"name\": \"use/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.1\", \"via\": \"\"},
\"remove/3.1\": { \"name\": \"remove/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/3.1\", \"via\": \"\"},
\"use/3.2\": { \"name\": \"use/3.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.2\", \"via\": \"\"},
\"loc_virt1/1.0\": { \"name\": \"loc_virt1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt1/.common\", \"via\": \"\"},
\"user/novice\": { \"name\": \"user/novice\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/novice\", \"via\": \"\"},
\"user/exp\": { \"name\": \"user/exp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/exp\", \"via\": \"\"},
\"loc_rc4/1.0\": { \"name\": \"loc_rc4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/1.0\", \"via\": \"\"},
\"loc_rc3/3.0\": { \"name\": \"loc_rc3/3.0\", \"type\": \"modulefile\", \"symbols\": \[ \"chk\", \"exp\", \"new\", \"test\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/3.0\", \"via\": \"\"},
\"continue/4.0\": { \"name\": \"continue/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/4.0\", \"via\": \"\"},
\"modbad/paths\": { \"name\": \"modbad/paths\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/paths\", \"via\": \"\"},
\"prereq/full\": { \"name\": \"prereq/full\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/full\", \"via\": \"\"},
\"info/command\": { \"name\": \"info/command\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/command\", \"via\": \"\"},
\"empty/1.0\": { \"name\": \"empty/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/empty/1.0\", \"via\": \"\"},
\"remove/0.3\": { \"name\": \"remove/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.3\", \"via\": \"\"},
\"remove/0.4\": { \"name\": \"remove/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.4\", \"via\": \"\"},
\"remove/0.5\": { \"name\": \"remove/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.5\", \"via\": \"\"},
\"help/2.0\": { \"name\": \"help/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/help/2.0\", \"via\": \"\"},
\"exit/2.0\": { \"name\": \"exit/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/2.0\", \"via\": \"\"},
\"loc_dv3/2.0\": { \"name\": \"loc_dv3/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv3/2.0\", \"via\": \"\"},
\"user/adv\": { \"name\": \"user/adv\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/adv\", \"via\": \"\"},
\"log/badfac\": { \"name\": \"log/badfac\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/badfac\", \"via\": \"\"},
\"loc_rc2/2.0\": { \"name\": \"loc_rc2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc2/2.0\", \"via\": \"\"},
\"system/1.0\": { \"name\": \"system/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/system/1.0\", \"via\": \"\"},
\"continue/1.0\": { \"name\": \"continue/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/1.0\", \"via\": \"\"},
\"info/type\": { \"name\": \"info/type\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/type\", \"via\": \"\"},
\"append/0.1\": { \"name\": \"append/0.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.1\", \"via\": \"\"},
\"load/00\": { \"name\": \"load/00\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/00\", \"via\": \"\"},
\"whatis/none\": { \"name\": \"whatis/none\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/none\", \"via\": \"\"},
\"append/0.2\": { \"name\": \"append/0.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.2\", \"via\": \"\"},
\"info/commandexp\": { \"name\": \"info/commandexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/commandexp\", \"via\": \"\"},
\"append/0.3\": { \"name\": \"append/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.3\", \"via\": \"\"},
\"append/0.4\": { \"name\": \"append/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.4\", \"via\": \"\"},
\"append/0.5\": { \"name\": \"append/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.5\", \"via\": \"\"},
\"prepend/8.0\": { \"name\": \"prepend/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/8.0\", \"via\": \"\"},
\"spread/8.0\": { \"name\": \"spread/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/8.0\", \"via\": \"\"},
\"module/relpath\": { \"name\": \"module/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/relpath\", \"via\": \"\"},
\"loc_dv2/1.0\": { \"name\": \"loc_dv2/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv2/1.0\", \"via\": \"\"},
\"spreadrc/dir7/1.0\": { \"name\": \"spreadrc/dir7/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir7/1.0\", \"via\": \"\"},
\"loc_sym/alias1\": { \"name\": \"loc_sym/alias1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias1\", \"via\": \"\"},
\"load/10\": { \"name\": \"load/10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/10\", \"via\": \"\"},
\"loc_sym/alias2\": { \"name\": \"loc_sym/alias2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias2\", \"via\": \"\"},
\"loc_rc1/1.0\": { \"name\": \"loc_rc1/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc1/1.0\", \"via\": \"\"},
\"load/11\": { \"name\": \"load/11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/11\", \"via\": \"\"},
\"conflict/relpath\": { \"name\": \"conflict/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/relpath\", \"via\": \"\"},
\"loc_sym/alias3\": { \"name\": \"loc_sym/alias3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias3\", \"via\": \"\"},
\"load/12\": { \"name\": \"load/12\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/12\", \"via\": \"\"},
\"loc_sym/alias4\": { \"name\": \"loc_sym/alias4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias4\", \"via\": \"\"},
\"load/13\": { \"name\": \"load/13\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/13\", \"via\": \"\"},
\"loc_sym/alias5\": { \"name\": \"loc_sym/alias5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias5\", \"via\": \"\"},
\"load/14\": { \"name\": \"load/14\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/14\", \"via\": \"\"},
\"loc_sym/alias6\": { \"name\": \"loc_sym/alias6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias6\", \"via\": \"\"},
\"load/15\": { \"name\": \"load/15\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/15\", \"via\": \"\"},
\"loc_sym/alias7\": { \"name\": \"loc_sym/alias7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias7\", \"via\": \"\"},
\"loc_sym/getvers10\": { \"name\": \"loc_sym/getvers10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers10\", \"via\": \"\"},
\"load/16\": { \"name\": \"load/16\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/16\", \"via\": \"\"},
\"loc_sym/alias8\": { \"name\": \"loc_sym/alias8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias8\", \"via\": \"\"},
\"load/17\": { \"name\": \"load/17\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/17\", \"via\": \"\"},
\"modbad/info-loaded\": { \"name\": \"modbad/info-loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/info-loaded\", \"via\": \"\"},
\"loc_sym/alias9\": { \"name\": \"loc_sym/alias9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias9\", \"via\": \"\"},
\"load/18\": { \"name\": \"load/18\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/18\", \"via\": \"\"},
\"spread/5.0\": { \"name\": \"spread/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/5.0\", \"via\": \"\"},
\"load/20\": { \"name\": \"load/20\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/20\", \"via\": \"\"},
\"load/19\": { \"name\": \"load/19\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/19\", \"via\": \"\"},
\"tr2_loc/al1\": { \"name\": \"tr2_loc/al1\", \"type\": \"alias\", \"symbols\": \[ \"tr2unstable\" \], \"tags\": \[\], \"target\": \"tr_loc/trunstable\", \"via\": \"\"},
\"load/21\": { \"name\": \"load/21\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/21\", \"via\": \"\"},
\"tr2_loc/al2\": { \"name\": \"tr2_loc/al2\", \"type\": \"alias\", \"symbols\": \[ \"tr2bar\" \], \"tags\": \[\], \"target\": \"tr_loc/trbar\", \"via\": \"\"},
\"averssort/1.2.4\": { \"name\": \"averssort/1.2.4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1.2.4\", \"via\": \"\"},
\"chdir/4.0\": { \"name\": \"chdir/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/4.0\", \"via\": \"\"},
\"load/22\": { \"name\": \"load/22\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/22\", \"via\": \"\"},
\"tr2_loc/al3\": { \"name\": \"tr2_loc/al3\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"tr2exp\", \"trreg\" \], \"tags\": \[\], \"target\": \"tr_loc/al2\", \"via\": \"\"},
\"dirmodvirt\": { \"name\": \"dirmodvirt\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"inforc/foo\": { \"name\": \"inforc/foo\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"inforc/1.0\", \"via\": \"\"},
\"load/23\": { \"name\": \"load/23\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/23\", \"via\": \"\"},
\"tr2_loc/al4\": { \"name\": \"tr2_loc/al4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"tr_loc/trexp\", \"via\": \"\"},
\"modbad/clear\": { \"name\": \"modbad/clear\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/clear\", \"via\": \"\"},
\"load/24\": { \"name\": \"load/24\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/24\", \"via\": \"\"},
\"tr2_loc/al5\": { \"name\": \"tr2_loc/al5\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"trreg\" \], \"tags\": \[\], \"target\": \"tr2_loc/tr2exp\", \"via\": \"\"},
\"load/25\": { \"name\": \"load/25\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/25\", \"via\": \"\"},
\"load/26\": { \"name\": \"load/26\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/26\", \"via\": \"\"},
\"inforc/2.0\": { \"name\": \"inforc/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"avail\", \"bar\", \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/inforc/2.0\", \"via\": \"\"},
\"load/27\": { \"name\": \"load/27\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/27\", \"via\": \"\"},
\"load/28\": { \"name\": \"load/28\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/28\", \"via\": \"\"},
\"log/err_syslog\": { \"name\": \"log/err_syslog\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_syslog\", \"via\": \"\"},
\"load/30\": { \"name\": \"load/30\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/30\", \"via\": \"\"},
\"load/29\": { \"name\": \"load/29\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/29\", \"via\": \"\"},
\"trace/all_on\": { \"name\": \"trace/all_on\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/trace/all_on\", \"via\": \"\"},
\"prepend/2.0\": { \"name\": \"prepend/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.0\", \"via\": \"\"},
\"loc_dv8/2.0\": { \"name\": \"loc_dv8/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv8/2.0\", \"via\": \"\"},
\"prepend/2.1\": { \"name\": \"prepend/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.1\", \"via\": \"\"},
\"spread/2.0\": { \"name\": \"spread/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/2.0\", \"via\": \"\"},
\"prepend/2.2\": { \"name\": \"prepend/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.2\", \"via\": \"\"},
\"break/5.0\": { \"name\": \"break/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/5.0\", \"via\": \"\"},
\"info/isused\": { \"name\": \"info/isused\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isused\", \"via\": \"\"},
\"chdir/1.0\": { \"name\": \"chdir/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/1.0\", \"via\": \"\"},
\"prepend/2.3\": { \"name\": \"prepend/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.3\", \"via\": \"\"},
\"prepend/2.4\": { \"name\": \"prepend/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.4\", \"via\": \"\"},
\"loc_tr\": { \"name\": \"loc_tr\", \"type\": \"directory\", \"symbols\": \[ \"reg\" \], \"via\": \"\"},
\"getenv/0.6\": { \"name\": \"getenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/getenv/0.6\", \"via\": \"\"},
\"verbose/msg\": { \"name\": \"verbose/msg\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/msg\", \"via\": \"\"},
\"spreadrc/dir4/1.0\": { \"name\": \"spreadrc/dir4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir4/1.0\", \"via\": \"\"},
\"prepend/1.10\": { \"name\": \"prepend/1.10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.10\", \"via\": \"\"},
\"bad2/body\": { \"name\": \"bad2/body\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad2/body\", \"via\": \"\"},
\"source/1.0\": { \"name\": \"source/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.0\", \"via\": \"\"},
\"loc_rc8/0.9\": { \"name\": \"loc_rc8/0.9\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc8/.2.0\", \"via\": \"\"},
\"source/1.1\": { \"name\": \"source/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.1\", \"via\": \"\"},
\"loc_tr/1.0\": { \"name\": \"loc_tr/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"cur\", \"stable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/1.0\", \"via\": \"\"},
\"info/mode1\": { \"name\": \"info/mode1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode1\", \"via\": \"\"},
\"source/1.2\": { \"name\": \"source/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.2\", \"via\": \"\"},
\"info/issaved\": { \"name\": \"info/issaved\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/issaved\", \"via\": \"\"},
\"info/mode2\": { \"name\": \"info/mode2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode2\", \"via\": \"\"},
\"info/mode3\": { \"name\": \"info/mode3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode3\", \"via\": \"\"},
\"module/unk\": { \"name\": \"module/unk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/unk\", \"via\": \"\"},
\"uname/unk\": { \"name\": \"uname/unk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/unk\", \"via\": \"\"},
\"info/isavail\": { \"name\": \"info/isavail\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isavail\", \"via\": \"\"},
\"info/mode4\": { \"name\": \"info/mode4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode4\", \"via\": \"\"},
\"break/2.0\": { \"name\": \"break/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/2.0\", \"via\": \"\"},
\"loc_dv7/1.0\": { \"name\": \"loc_dv7/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/1.0\", \"via\": \"\"},
\"info/mode5\": { \"name\": \"info/mode5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode5\", \"via\": \"\"},
\"info/mode6\": { \"name\": \"info/mode6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode6\", \"via\": \"\"},
\"loc_rc6/1.2\": { \"name\": \"loc_rc6/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc6/1.2\", \"via\": \"\"},
\"tr_loc/al1\": { \"name\": \"tr_loc/al1\", \"type\": \"alias\", \"symbols\": \[ \"tr2unstable\", \"trunstable\" \], \"tags\": \[\], \"target\": \"loc_tr/next\", \"via\": \"\"},
\"versions/1.1\": { \"name\": \"versions/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.1\", \"via\": \"\"},
\"setenv/0.7.1\": { \"name\": \"setenv/0.7.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.7.1\", \"via\": \"\"},
\"tr_loc/al2\": { \"name\": \"tr_loc/al2\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"tr2bar\", \"tr2exp\", \"trbar\", \"trreg\" \], \"tags\": \[\], \"target\": \"loc_tr/foo\", \"via\": \"\"},
\"loc_rcv2/2.0\": { \"name\": \"loc_rcv2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv2/.common\", \"via\": \"\"},
\"loc_rc7/1\": { \"name\": \"loc_rc7/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc7/1.2\", \"via\": \"\"},
\"log/err_file\": { \"name\": \"log/err_file\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_file\", \"via\": \"\"},
\"versions/1.2\": { \"name\": \"versions/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.2\", \"via\": \"\"},
\"setenv/0.7.2\": { \"name\": \"setenv/0.7.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.7.2\", \"via\": \"\"},
\"tr_loc/al3\": { \"name\": \"tr_loc/al3\", \"type\": \"alias\", \"symbols\": \[ \"trexp\" \], \"tags\": \[\], \"target\": \"loc_tr/al2\", \"via\": \"\"},
\"versions/1.3\": { \"name\": \"versions/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.3\", \"via\": \"\"},
\"alias/3.0\": { \"name\": \"alias/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/3.0\", \"via\": \"\"},
\"tr_loc/al4\": { \"name\": \"tr_loc/al4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_tr/exp\", \"via\": \"\"},
\"tr_loc/al5\": { \"name\": \"tr_loc/al5\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"tr_loc/trexp\", \"via\": \"\"},
\"info/name\": { \"name\": \"info/name\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/name\", \"via\": \"\"},
\"append/7.0\": { \"name\": \"append/7.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/7.0\", \"via\": \"\"},
\"use/4.0\": { \"name\": \"use/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/4.0\", \"via\": \"\"},
\"use/4.1\": { \"name\": \"use/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/4.1\", \"via\": \"\"},
\"symlink2/1.0\": { \"name\": \"symlink2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink2/1.0\", \"via\": \"\"},
\"remove/4.0\": { \"name\": \"remove/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.0\", \"via\": \"\"},
\"conflict/module\": { \"name\": \"conflict/module\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/module\", \"via\": \"\"},
\"loc_sym/alias10\": { \"name\": \"loc_sym/alias10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias10\", \"via\": \"\"},
\"remove/4.1\": { \"name\": \"remove/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.1\", \"via\": \"\"},
\"loc_sym/alias11\": { \"name\": \"loc_sym/alias11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias11\", \"via\": \"\"},
\"remove/4.2\": { \"name\": \"remove/4.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.2\", \"via\": \"\"},
\"loc_virt1/2.0\": { \"name\": \"loc_virt1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt1/.common\", \"via\": \"\"},
\"loc_sym/versinf1\": { \"name\": \"loc_sym/versinf1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf1\", \"via\": \"\"},
\"loc_sym/1.0\": { \"name\": \"loc_sym/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/1.0\", \"via\": \"\"},
\"loc_sym/versinf2\": { \"name\": \"loc_sym/versinf2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf2\", \"via\": \"\"},
\"loc_rc4/2.0\": { \"name\": \"loc_rc4/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/2.0\", \"via\": \"\"},
\"loc_sym/versinf3\": { \"name\": \"loc_sym/versinf3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf3\", \"via\": \"\"},
\"loc_sym/versinf4\": { \"name\": \"loc_sym/versinf4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf4\", \"via\": \"\"},
\"info/specified\": { \"name\": \"info/specified\", \"type\": \"modulefile\", \"symbols\": \[ \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/info/specified\", \"via\": \"\"},
\"loc_sym/versinf5\": { \"name\": \"loc_sym/versinf5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf5\", \"via\": \"\"},
\"continue/5.0\": { \"name\": \"continue/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/5.0\", \"via\": \"\"},
\"loc_rcv1/1.1\": { \"name\": \"loc_rcv1/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.base\", \"via\": \"\"},
\"loc_sym/versinf6\": { \"name\": \"loc_sym/versinf6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf6\", \"via\": \"\"},
\"loc_rcv1/1.2\": { \"name\": \"loc_rcv1/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"append/4.0\": { \"name\": \"append/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/4.0\", \"via\": \"\"},
\"loc_sym/versinf7\": { \"name\": \"loc_sym/versinf7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf7\", \"via\": \"\"},
\"spreadrc/dir1/1.0\": { \"name\": \"spreadrc/dir1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir1/1.0\", \"via\": \"\"},
\"append/4.1\": { \"name\": \"append/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/4.1\", \"via\": \"\"},
\"use/1.0\": { \"name\": \"use/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/use/1.0\", \"via\": \"\"},
\"bad2/proc\": { \"name\": \"bad2/proc\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad2/proc\", \"via\": \"\"},
\"remove/1.0\": { \"name\": \"remove/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.0\", \"via\": \"\"},
\"module/err\": { \"name\": \"module/err\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/err\", \"via\": \"\"},
\"modbad/remove-path\": { \"name\": \"modbad/remove-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/remove-path\", \"via\": \"\"},
\"modbad/sh-to-mod\": { \"name\": \"modbad/sh-to-mod\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/sh-to-mod\", \"via\": \"\"},
\"modbad/edit\": { \"name\": \"modbad/edit\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/edit\", \"via\": \"\"},
\"remove/1.3\": { \"name\": \"remove/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.3\", \"via\": \"\"},
\"remove/1.4\": { \"name\": \"remove/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.4\", \"via\": \"\"},
\"uname/cache\": { \"name\": \"uname/cache\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/cache\", \"via\": \"\"},
\"loc_dv4/1.0\": { \"name\": \"loc_dv4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv4/1.0\", \"via\": \"\"},
\"remove/1.5\": { \"name\": \"remove/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.5\", \"via\": \"\"},
\"loc_fq/1.0\": { \"name\": \"loc_fq/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_fq/1.0\", \"via\": \"\"},
\"exit/3.0\": { \"name\": \"exit/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/3.0\", \"via\": \"\"},
\"remove/1.6\": { \"name\": \"remove/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.6\", \"via\": \"\"},
\"loc_rc3/1.0\": { \"name\": \"loc_rc3/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/1.0\", \"via\": \"\"},
\"unsetenv/0.6\": { \"name\": \"unsetenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.6\", \"via\": \"\"},
\"whatis/multiple\": { \"name\": \"whatis/multiple\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/multiple\", \"via\": \"\"},
\"remove/1.7\": { \"name\": \"remove/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.7\", \"via\": \"\"},
\"continue/2.0\": { \"name\": \"continue/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/2.0\", \"via\": \"\"},
\"system/2.0\": { \"name\": \"system/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/system/2.0\", \"via\": \"\"},
\"remove/1.8\": { \"name\": \"remove/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.8\", \"via\": \"\"},
\"unsetenv/0.8\": { \"name\": \"unsetenv/0.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.8\", \"via\": \"\"},
\"unsetenv/0.9\": { \"name\": \"unsetenv/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.9\", \"via\": \"\"},
\"append/1.0\": { \"name\": \"append/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.0\", \"via\": \"\"},
\"append/1.1\": { \"name\": \"append/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.1\", \"via\": \"\"},
\"verbose/off\": { \"name\": \"verbose/off\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/off\", \"via\": \"\"},
\"append/1.3\": { \"name\": \"append/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.3\", \"via\": \"\"},
\"loc_def/truedef\": { \"name\": \"loc_def/truedef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_def/truedef\", \"via\": \"\"},
\"append/1.4\": { \"name\": \"append/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.4\", \"via\": \"\"},
\"append/1.5\": { \"name\": \"append/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.5\", \"via\": \"\"},
\"module/meta\": { \"name\": \"module/meta\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/meta\", \"via\": \"\"},
\"module/empty\": { \"name\": \"module/empty\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/empty\", \"via\": \"\"},
\"append/1.6\": { \"name\": \"append/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.6\", \"via\": \"\"},
\"append/1.7\": { \"name\": \"append/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.7\", \"via\": \"\"},
\"info/shells\": { \"name\": \"info/shells\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/shells\", \"via\": \"\"},
\"append/1.8\": { \"name\": \"append/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.8\", \"via\": \"\"},
\"loc_dv2/2.0\": { \"name\": \"loc_dv2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv2/2.0\", \"via\": \"\"},
\"loc_rc1/2.0\": { \"name\": \"loc_rc1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc1/2.0\", \"via\": \"\"},
\"symlink/bar\": { \"name\": \"symlink/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"symlink/1.2\", \"via\": \"\"},
\"loc_sym/exec1\": { \"name\": \"loc_sym/exec1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec1\", \"via\": \"\"},
\"prereq/orlist\": { \"name\": \"prereq/orlist\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/orlist\", \"via\": \"\"},
\"loc_sym/exec2\": { \"name\": \"loc_sym/exec2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec2\", \"via\": \"\"},
\"loc_rc7/bar\": { \"name\": \"loc_rc7/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc7/0.9\", \"via\": \"\"},
\"loc_sym/exec3\": { \"name\": \"loc_sym/exec3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec3\", \"via\": \"\"},
\"modbad/empty\": { \"name\": \"modbad/empty\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/empty\", \"via\": \"\"},
\"module/lunk\": { \"name\": \"module/lunk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lunk\", \"via\": \"\"},
\"modvar/modfile\": { \"name\": \"modvar/modfile\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modvar/modfile\", \"via\": \"\"},
\"loc_rc010/2.0\": { \"name\": \"loc_rc010/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc010/2.0\", \"via\": \"\"},
\"spread/6.0\": { \"name\": \"spread/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/6.0\", \"via\": \"\"},
\"verbose/on\": { \"name\": \"verbose/on\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/on\", \"via\": \"\"},
\"loc_sym/version10\": { \"name\": \"loc_sym/version10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version10\", \"via\": \"\"},
\"x-resource/1\": { \"name\": \"x-resource/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/x-resource/1\", \"via\": \"\"},
\"loc_sym/version11\": { \"name\": \"loc_sym/version11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version11\", \"via\": \"\"},
\"log/err_both_1\": { \"name\": \"log/err_both_1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_both_1\", \"via\": \"\"},
\"loc_sym/version12\": { \"name\": \"loc_sym/version12\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version12\", \"via\": \"\"},
\"loc_dv1/1.0\": { \"name\": \"loc_dv1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv1/1.0\", \"via\": \"\"},
\"spreadrc/dir6/1.0\": { \"name\": \"spreadrc/dir6/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir6/1.0\", \"via\": \"\"},
\"loc_sym/version13\": { \"name\": \"loc_sym/version13\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version13\", \"via\": \"\"},
\"info/userexp\": { \"name\": \"info/userexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/userexp\", \"via\": \"\"},
\"log/err_both_2\": { \"name\": \"log/err_both_2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_both_2\", \"via\": \"\"},
\"modbad/is-used\": { \"name\": \"modbad/is-used\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-used\", \"via\": \"\"},
\"loc_sym/version14\": { \"name\": \"loc_sym/version14\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version14\", \"via\": \"\"},
\"loc_sym/version15\": { \"name\": \"loc_sym/version15\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version15\", \"via\": \"\"},
\"loc_sym/version16\": { \"name\": \"loc_sym/version16\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version16\", \"via\": \"\"},
\"loc_sym/version17\": { \"name\": \"loc_sym/version17\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version17\", \"via\": \"\"},
\"loc_sym/version18\": { \"name\": \"loc_sym/version18\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version18\", \"via\": \"\"},
\"recurs/modA\": { \"name\": \"recurs/modA\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/recurs/modA\", \"via\": \"\"},
\"tr2_loc\": { \"name\": \"tr2_loc\", \"type\": \"directory\", \"symbols\": \[ \"trreg\" \], \"via\": \"\"},
\"loc_sym/version19\": { \"name\": \"loc_sym/version19\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version19\", \"via\": \"\"},
\"loc_sym/version20\": { \"name\": \"loc_sym/version20\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version20\", \"via\": \"\"},
\"recurs/modB\": { \"name\": \"recurs/modB\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/recurs/modB\", \"via\": \"\"},
\"loc_dv9/1.0\": { \"name\": \"loc_dv9/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv9/1.0\", \"via\": \"\"},
\"loc_sym/version21\": { \"name\": \"loc_sym/version21\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version21\", \"via\": \"\"},
\"prepend/3.0\": { \"name\": \"prepend/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/3.0\", \"via\": \"\"},
\"getenv/1.0\": { \"name\": \"getenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/getenv/1.0\", \"via\": \"\"},
\"loc_sym/version22\": { \"name\": \"loc_sym/version22\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version22\", \"via\": \"\"},
\"prepend/3.1\": { \"name\": \"prepend/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/3.1\", \"via\": \"\"},
\"spread/3.0\": { \"name\": \"spread/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/3.0\", \"via\": \"\"},
\"loc_sym/version23\": { \"name\": \"loc_sym/version23\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version23\", \"via\": \"\"},
\"break/6.0\": { \"name\": \"break/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/6.0\", \"via\": \"\"},
\"loc_rc8/1.0\": { \"name\": \"loc_rc8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc8/1.0\", \"via\": \"\"},
\"loc_sym/version24\": { \"name\": \"loc_sym/version24\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version24\", \"via\": \"\"},
\"chdir/2.0\": { \"name\": \"chdir/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/2.0\", \"via\": \"\"},
\"loc_sym/version25\": { \"name\": \"loc_sym/version25\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version25\", \"via\": \"\"},
\"coll/a\": { \"name\": \"coll/a\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/a\", \"via\": \"\"},
\"coll/b\": { \"name\": \"coll/b\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/b\", \"via\": \"\"},
\"loc_sym/version26\": { \"name\": \"loc_sym/version26\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version26\", \"via\": \"\"},
\"coll/c\": { \"name\": \"coll/c\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/c\", \"via\": \"\"},
\"coll/d\": { \"name\": \"coll/d\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/d\", \"via\": \"\"},
\"test/1.0\": { \"name\": \"test/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/1.0\", \"via\": \"\"},
\"test/1.2\": { \"name\": \"test/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/1.2\", \"via\": \"\"},
\"user/nov\": { \"name\": \"user/nov\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/nov\", \"via\": \"\"},
\"conflict/fullpath\": { \"name\": \"conflict/fullpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/fullpath\", \"via\": \"\"},
\"loc_tr/2.0\": { \"name\": \"loc_tr/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"next\", \"tr2unstable\", \"trunstable\", \"unstable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/2.0\", \"via\": \"\"},
\"module/lerr\": { \"name\": \"module/lerr\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lerr\", \"via\": \"\"},
\"uname/version\": { \"name\": \"uname/version\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/version\", \"via\": \"\"},
\"remove/8.0\": { \"name\": \"remove/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/8.0\", \"via\": \"\"},
\"prepend/0.1\": { \"name\": \"prepend/0.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.1\", \"via\": \"\"},
\"loc_dv7/2.0\": { \"name\": \"loc_dv7/2.0\", \"type\": \"directory\", \"symbols\": \[ \"default\" \], \"via\": \"\"},
\"module/2.0\": { \"name\": \"module/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/2.0\", \"via\": \"\"},
\"prepend/0.2\": { \"name\": \"prepend/0.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.2\", \"via\": \"\"},
\"break/3.0\": { \"name\": \"break/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/3.0\", \"via\": \"\"},
\"modbad/prepend-path\": { \"name\": \"modbad/prepend-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/prepend-path\", \"via\": \"\"},
\"prepend/0.3\": { \"name\": \"prepend/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.3\", \"via\": \"\"},
\"dirmodalias/1.0\": { \"name\": \"dirmodalias/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/dirmodalias/1.0\", \"via\": \"\"},
\"prepend/0.4\": { \"name\": \"prepend/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.4\", \"via\": \"\"},
\"verssort/1.2.1\": { \"name\": \"verssort/1.2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.2.1\", \"via\": \"\"},
\"modbad/is-loaded\": { \"name\": \"modbad/is-loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-loaded\", \"via\": \"\"},
\"prepend/0.5\": { \"name\": \"prepend/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.5\", \"via\": \"\"},
\"verssort/1.2.4\": { \"name\": \"verssort/1.2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.2.4\", \"via\": \"\"},
\"loc_dv6/2.0/1.0\": { \"name\": \"loc_dv6/2.0/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv6/2.0/1.0\", \"via\": \"\"},
\"spreadrc/dir3/1.0\": { \"name\": \"spreadrc/dir3/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir3/1.0\", \"via\": \"\"},
\"loc_dvv1/1.0\": { \"name\": \"loc_dvv1/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dvv1/.common\", \"via\": \"\"},
\"append/8.0\": { \"name\": \"append/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/8.0\", \"via\": \"\"},
\"symlink/0.9\": { \"name\": \"symlink/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink/0.9\", \"via\": \"\"},
\"loc_rc7/0.9\": { \"name\": \"loc_rc7/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc7/0.9\", \"via\": \"\"}
}}"

set ts_sh_all_json "{\"$modpath\": {
\"loc_tr/al1\": { \"name\": \"loc_tr/al1\", \"type\": \"alias\", \"symbols\": \[ \"unstable\" \], \"tags\": \[\], \"target\": \"loc_tr/next\", \"via\": \"\"},
\"remove/5.0\": { \"name\": \"remove/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/5.0\", \"via\": \"\"},
\"symlink2/2.0\": { \"name\": \"symlink2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink2/2.0\", \"via\": \"\"},
\"loc_def/default\": { \"name\": \"loc_def/default\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_def/default\", \"via\": \"\"},
\"loc_tr/al2\": { \"name\": \"loc_tr/al2\", \"type\": \"alias\", \"symbols\": \[ \"bar\", \"default\", \"exp\", \"reg\", \"trexp\" \], \"tags\": \[\], \"target\": \"loc_tr/foo\", \"via\": \"\"},
\"verssort/1.8-2015-12-01\": { \"name\": \"verssort/1.8-2015-12-01\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.8-2015-12-01\", \"via\": \"\"},
\"whatis/single\": { \"name\": \"whatis/single\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/single\", \"via\": \"\"},
\"loc_virt2/1.0\": { \"name\": \"loc_virt2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt2/2.0\", \"via\": \"\"},
\"loc_tr/al3\": { \"name\": \"loc_tr/al3\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"exp\", \"reg\" \], \"tags\": \[\], \"target\": \"loc_tr/al2\", \"via\": \"\"},
\"uname/machine\": { \"name\": \"uname/machine\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/machine\", \"via\": \"\"},
\"loc_virt1/3.0\": { \"name\": \"loc_virt1/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_virt\", \"via\": \"\"},
\"loc_tr/al4\": { \"name\": \"loc_tr/al4\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"reg\" \], \"tags\": \[\], \"target\": \"loc_tr/exp\", \"via\": \"\"},
\"loc_dv6/1.0\": { \"name\": \"loc_dv6/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv6/1.0\", \"via\": \"\"},
\"function/1.0\": { \"name\": \"function/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/function/1.0\", \"via\": \"\"},
\"loc_rc5/1.0\": { \"name\": \"loc_rc5/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc5/1.0\", \"via\": \"\"},
\"whatis/string\": { \"name\": \"whatis/string\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/string\", \"via\": \"\"},
\"loc_rc4/3.0\": { \"name\": \"loc_rc4/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/3.0\", \"via\": \"\"},
\"loc_rcv1/2.0\": { \"name\": \"loc_rcv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"continue/6.0\": { \"name\": \"continue/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/6.0\", \"via\": \"\"},
\"alias/1.0\": { \"name\": \"alias/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/1.0\", \"via\": \"\"},
\"setenv/0.6\": { \"name\": \"setenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.6\", \"via\": \"\"},
\"append/5.0\": { \"name\": \"append/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/5.0\", \"via\": \"\"},
\"setenv/0.8\": { \"name\": \"setenv/0.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.8\", \"via\": \"\"},
\"use/2.0\": { \"name\": \"use/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.0\", \"via\": \"\"},
\"use/2.1\": { \"name\": \"use/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.1\", \"via\": \"\"},
\"remove/2.0\": { \"name\": \"remove/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.0\", \"via\": \"\"},
\"unsetenv/1.0\": { \"name\": \"unsetenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/1.0\", \"via\": \"\"},
\"use/2.2\": { \"name\": \"use/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/2.2\", \"via\": \"\"},
\"verssort/1.10\": { \"name\": \"verssort/1.10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.10\", \"via\": \"\"},
\"user/undef\": { \"name\": \"user/undef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/undef\", \"via\": \"\"},
\"bad/after\": { \"name\": \"bad/after\", \"type\": \"modulefile\", \"symbols\": \[ \"good\" \], \"tags\": \[\], \"pathname\": \"$modpath/bad/after\", \"via\": \"\"},
\"remove/2.3\": { \"name\": \"remove/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.3\", \"via\": \"\"},
\"remove/2.4\": { \"name\": \"remove/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/2.4\", \"via\": \"\"},
\"info/user\": { \"name\": \"info/user\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/user\", \"via\": \"\"},
\"exit/4.0\": { \"name\": \"exit/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/4.0\", \"via\": \"\"},
\"modbad/autoinit\": { \"name\": \"modbad/autoinit\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/autoinit\", \"via\": \"\"},
\"loc_rc3/2.0\": { \"name\": \"loc_rc3/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"cur\", \"stable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/2.0\", \"via\": \"\"},
\"puts/1\": { \"name\": \"puts/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/1\", \"via\": \"\"},
\"puts/2\": { \"name\": \"puts/2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/2\", \"via\": \"\"},
\"uname/domain\": { \"name\": \"uname/domain\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/domain\", \"via\": \"\"},
\"uname/sysname\": { \"name\": \"uname/sysname\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/sysname\", \"via\": \"\"},
\"continue/3.0\": { \"name\": \"continue/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/3.0\", \"via\": \"\"},
\"puts/3\": { \"name\": \"puts/3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/3\", \"via\": \"\"},
\"puts/4\": { \"name\": \"puts/4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/4\", \"via\": \"\"},
\"append/2.0\": { \"name\": \"append/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.0\", \"via\": \"\"},
\"puts/5\": { \"name\": \"puts/5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/5\", \"via\": \"\"},
\"modbad/append-path\": { \"name\": \"modbad/append-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/append-path\", \"via\": \"\"},
\"append/2.1\": { \"name\": \"append/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.1\", \"via\": \"\"},
\"loc_rcv1/1\": { \"name\": \"loc_rcv1/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rcv1/1.2\", \"via\": \"\"},
\"append/2.2\": { \"name\": \"append/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.2\", \"via\": \"\"},
\"puts/6\": { \"name\": \"puts/6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/6\", \"via\": \"\"},
\"append/2.3\": { \"name\": \"append/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.3\", \"via\": \"\"},
\"puts/7\": { \"name\": \"puts/7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/7\", \"via\": \"\"},
\"modbad/path\": { \"name\": \"modbad/path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/path\", \"via\": \"\"},
\"append/2.4\": { \"name\": \"append/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/2.4\", \"via\": \"\"},
\"puts/8\": { \"name\": \"puts/8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/8\", \"via\": \"\"},
\"puts/9\": { \"name\": \"puts/9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/puts/9\", \"via\": \"\"},
\"user/advanced\": { \"name\": \"user/advanced\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/advanced\", \"via\": \"\"},
\"uname/release\": { \"name\": \"uname/release\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/release\", \"via\": \"\"},
\"spreadrc/dir8/1.0\": { \"name\": \"spreadrc/dir8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir8/1.0\", \"via\": \"\"},
\"exit/1.0\": { \"name\": \"exit/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/1.0\", \"via\": \"\"},
\"loc_dv3/1.0\": { \"name\": \"loc_dv3/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv3/1.0\", \"via\": \"\"},
\"loc_rc2/1.0\": { \"name\": \"loc_rc2/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"bar\", \"blah\", \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc2/1.0\", \"via\": \"\"},
\"modbad/config\": { \"name\": \"modbad/config\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/config\", \"via\": \"\"},
\"module/bad\": { \"name\": \"module/bad\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/bad\", \"via\": \"\"},
\"prereq/fullpath\": { \"name\": \"prereq/fullpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/fullpath\", \"via\": \"\"},
\"loc_sym/getvers1\": { \"name\": \"loc_sym/getvers1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers1\", \"via\": \"\"},
\"verbose/undef\": { \"name\": \"verbose/undef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/undef\", \"via\": \"\"},
\"loc_sym/getvers2\": { \"name\": \"loc_sym/getvers2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers2\", \"via\": \"\"},
\"loc_sym/getvers3\": { \"name\": \"loc_sym/getvers3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers3\", \"via\": \"\"},
\"loc_sym/getvers4\": { \"name\": \"loc_sym/getvers4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers4\", \"via\": \"\"},
\"loc_sym/getvers5\": { \"name\": \"loc_sym/getvers5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers5\", \"via\": \"\"},
\"modbad/is-saved\": { \"name\": \"modbad/is-saved\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-saved\", \"via\": \"\"},
\"modbad/foo\": { \"name\": \"modbad/foo\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/foo\", \"via\": \"\"},
\"modvar/submodfile\": { \"name\": \"modvar/submodfile\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modvar/submodfile\", \"via\": \"\"},
\"spread/7.0\": { \"name\": \"spread/7.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/7.0\", \"via\": \"\"},
\"loc_sym/getvers6\": { \"name\": \"loc_sym/getvers6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers6\", \"via\": \"\"},
\"modbad/is-avail\": { \"name\": \"modbad/is-avail\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-avail\", \"via\": \"\"},
\"loc_sym/getvers7\": { \"name\": \"loc_sym/getvers7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers7\", \"via\": \"\"},
\"loc_sym/getvers8\": { \"name\": \"loc_sym/getvers8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers8\", \"via\": \"\"},
\"loc_sym/getvers9\": { \"name\": \"loc_sym/getvers9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers9\", \"via\": \"\"},
\"loc_dv1/2.0\": { \"name\": \"loc_dv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv1/2.0\", \"via\": \"\"},
\"info/isloaded\": { \"name\": \"info/isloaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isloaded\", \"via\": \"\"},
\"dirmodalias\": { \"name\": \"dirmodalias\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6\", \"via\": \"\"},
\"dirmodvirt/1.0\": { \"name\": \"dirmodvirt/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"loc_rc6/bar\": { \"name\": \"loc_rc6/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6/1.2\", \"via\": \"\"},
\"prepend/4.0\": { \"name\": \"prepend/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/4.0\", \"via\": \"\"},
\"loc_dv9/2.0\": { \"name\": \"loc_dv9/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv9/2.0\", \"via\": \"\"},
\"load/all\": { \"name\": \"load/all\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/load/all\", \"via\": \"\"},
\"spread/4.0\": { \"name\": \"spread/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/4.0\", \"via\": \"\"},
\"chdir/3.0\": { \"name\": \"chdir/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/3.0\", \"via\": \"\"},
\"loc_dv7/2.0/1.0\": { \"name\": \"loc_dv7/2.0/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/2.0/1.0\", \"via\": \"\"},
\"info/shellsexp\": { \"name\": \"info/shellsexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/shellsexp\", \"via\": \"\"},
\"spreadrc/dir5/1.0\": { \"name\": \"spreadrc/dir5/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir5/1.0\", \"via\": \"\"},
\"inforc/1.0\": { \"name\": \"inforc/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/inforc/1.0\", \"via\": \"\"},
\"test/2.0\": { \"name\": \"test/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/2.0\", \"via\": \"\"},
\"info/others\": { \"name\": \"info/others\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/others\", \"via\": \"\"},
\"loc_tr/3.0\": { \"name\": \"loc_tr/3.0\", \"type\": \"modulefile\", \"symbols\": \[ \"bar\", \"default\", \"exp\", \"foo\", \"reg\", \"tr2bar\", \"tr2exp\", \"trbar\", \"trexp\", \"trreg\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/3.0\", \"via\": \"\"},
\"prepend/1.0\": { \"name\": \"prepend/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.0\", \"via\": \"\"},
\"loc_rcv1/bar\": { \"name\": \"loc_rcv1/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rcv1/1.2\", \"via\": \"\"},
\"spread/1.0\": { \"name\": \"spread/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/1.0\", \"via\": \"\"},
\"prepend/1.1\": { \"name\": \"prepend/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.1\", \"via\": \"\"},
\"loc_dv8/1.0\": { \"name\": \"loc_dv8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv8/1.0\", \"via\": \"\"},
\"loc_dv7/3.0\": { \"name\": \"loc_dv7/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/3.0\", \"via\": \"\"},
\"break/4.0\": { \"name\": \"break/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/4.0\", \"via\": \"\"},
\"symlink/1.2\": { \"name\": \"symlink/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/symlink/1.2\", \"via\": \"\"},
\"symlink/1\": { \"name\": \"symlink/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"symlink/1.2\", \"via\": \"\"},
\"prepend/1.3\": { \"name\": \"prepend/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.3\", \"via\": \"\"},
\"prepend/1.4\": { \"name\": \"prepend/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.4\", \"via\": \"\"},
\"averssort/1\": { \"name\": \"averssort/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1\", \"via\": \"\"},
\"prepend/1.5\": { \"name\": \"prepend/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.5\", \"via\": \"\"},
\"trace/all_off\": { \"name\": \"trace/all_off\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/trace/all_off\", \"via\": \"\"},
\"loc_rc7/1.2\": { \"name\": \"loc_rc7/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc7/1.2\", \"via\": \"\"},
\"bad/before\": { \"name\": \"bad/before\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad/before\", \"via\": \"\"},
\"prepend/1.6\": { \"name\": \"prepend/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.6\", \"via\": \"\"},
\"whatis/lines\": { \"name\": \"whatis/lines\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/lines\", \"via\": \"\"},
\"prepend/1.7\": { \"name\": \"prepend/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.7\", \"via\": \"\"},
\"prepend/1.8\": { \"name\": \"prepend/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.8\", \"via\": \"\"},
\"loc_sym/version1\": { \"name\": \"loc_sym/version1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version1\", \"via\": \"\"},
\"uname/nodename\": { \"name\": \"uname/nodename\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/nodename\", \"via\": \"\"},
\"loc_dvv1/2.0\": { \"name\": \"loc_dvv1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dvv1/.common\", \"via\": \"\"},
\"prepend/1.9\": { \"name\": \"prepend/1.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.9\", \"via\": \"\"},
\"loc_sym/version2\": { \"name\": \"loc_sym/version2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version2\", \"via\": \"\"},
\"prereq/relpath\": { \"name\": \"prereq/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/relpath\", \"via\": \"\"},
\"loc_sym/version3\": { \"name\": \"loc_sym/version3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version3\", \"via\": \"\"},
\"loc_sym/version4\": { \"name\": \"loc_sym/version4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version4\", \"via\": \"\"},
\"loc_sym/version5\": { \"name\": \"loc_sym/version5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version5\", \"via\": \"\"},
\"verssort/1.8-2016-02-01\": { \"name\": \"verssort/1.8-2016-02-01\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.8-2016-02-01\", \"via\": \"\"},
\"loc_sym/version6\": { \"name\": \"loc_sym/version6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version6\", \"via\": \"\"},
\"loc_sym/version7\": { \"name\": \"loc_sym/version7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version7\", \"via\": \"\"},
\"setenv/1.0\": { \"name\": \"setenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/1.0\", \"via\": \"\"},
\"break/1.0\": { \"name\": \"break/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/1.0\", \"via\": \"\"},
\"loc_virt2/2.0\": { \"name\": \"loc_virt2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt2/2.0\", \"via\": \"\"},
\"loc_sym/version8\": { \"name\": \"loc_sym/version8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version8\", \"via\": \"\"},
\"loc_virt1/4.0\": { \"name\": \"loc_virt1/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_virt\", \"via\": \"\"},
\"conflict/full\": { \"name\": \"conflict/full\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/full\", \"via\": \"\"},
\"prereq/module\": { \"name\": \"prereq/module\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/module\", \"via\": \"\"},
\"loc_sym/version9\": { \"name\": \"loc_sym/version9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version9\", \"via\": \"\"},
\"function/2.0\": { \"name\": \"function/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/function/2.0\", \"via\": \"\"},
\"user/expert\": { \"name\": \"user/expert\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/expert\", \"via\": \"\"},
\"loc_rc5/2.0\": { \"name\": \"loc_rc5/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc5/2.0\", \"via\": \"\"},
\"eschars/1.0\": { \"name\": \"eschars/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/eschars/1.0\", \"via\": \"\"},
\"modbad/help\": { \"name\": \"modbad/help\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/help\", \"via\": \"\"},
\"source/0.9\": { \"name\": \"source/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/0.9\", \"via\": \"\"},
\"loc_rc6/1\": { \"name\": \"loc_rc6/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc6/1.2\", \"via\": \"\"},
\"averssort/1.10\": { \"name\": \"averssort/1.10\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1.10\", \"via\": \"\"},
\"verssort/1\": { \"name\": \"verssort/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1\", \"via\": \"\"},
\"module/lbad\": { \"name\": \"module/lbad\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lbad\", \"via\": \"\"},
\"alias/2.0\": { \"name\": \"alias/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/2.0\", \"via\": \"\"},
\"loc_rcv2/1.2\": { \"name\": \"loc_rcv2/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv2/.common\", \"via\": \"\"},
\"spreadrc/dir2/1.0\": { \"name\": \"spreadrc/dir2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir2/1.0\", \"via\": \"\"},
\"append/6.0\": { \"name\": \"append/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/6.0\", \"via\": \"\"},
\"info/loaded\": { \"name\": \"info/loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/loaded\", \"via\": \"\"},
\"loc_rcv2/1.5\": { \"name\": \"loc_rcv2/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$env(TESTSUITEDIR)/virttargets/loc_rcv\", \"via\": \"\"},
\"use/3.0\": { \"name\": \"use/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.0\", \"via\": \"\"},
\"remove/3.0\": { \"name\": \"remove/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/3.0\", \"via\": \"\"},
\"loc_rc6/0.9\": { \"name\": \"loc_rc6/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc6/0.9\", \"via\": \"\"},
\"use/3.1\": { \"name\": \"use/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.1\", \"via\": \"\"},
\"remove/3.1\": { \"name\": \"remove/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/3.1\", \"via\": \"\"},
\"use/3.2\": { \"name\": \"use/3.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/3.2\", \"via\": \"\"},
\"loc_virt1/1.0\": { \"name\": \"loc_virt1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt1/.common\", \"via\": \"\"},
\"loc_virt1/.common\": { \"name\": \"loc_virt1/.common\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_virt1/.common\", \"via\": \"\"},
\"user/novice\": { \"name\": \"user/novice\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/novice\", \"via\": \"\"},
\"user/exp\": { \"name\": \"user/exp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/exp\", \"via\": \"\"},
\"loc_rc4/1.0\": { \"name\": \"loc_rc4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/1.0\", \"via\": \"\"},
\"loc_rc3/3.0\": { \"name\": \"loc_rc3/3.0\", \"type\": \"modulefile\", \"symbols\": \[ \"chk\", \"exp\", \"new\", \"test\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/3.0\", \"via\": \"\"},
\"continue/4.0\": { \"name\": \"continue/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/4.0\", \"via\": \"\"},
\"modbad/paths\": { \"name\": \"modbad/paths\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/paths\", \"via\": \"\"},
\"prereq/full\": { \"name\": \"prereq/full\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/full\", \"via\": \"\"},
\"info/command\": { \"name\": \"info/command\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/command\", \"via\": \"\"},
\"empty/1.0\": { \"name\": \"empty/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/empty/1.0\", \"via\": \"\"},
\"remove/0.3\": { \"name\": \"remove/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.3\", \"via\": \"\"},
\"remove/0.4\": { \"name\": \"remove/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.4\", \"via\": \"\"},
\"remove/0.5\": { \"name\": \"remove/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/0.5\", \"via\": \"\"},
\"help/2.0\": { \"name\": \"help/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/help/2.0\", \"via\": \"\"},
\"exit/2.0\": { \"name\": \"exit/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/2.0\", \"via\": \"\"},
\"loc_dv3/2.0\": { \"name\": \"loc_dv3/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv3/2.0\", \"via\": \"\"},
\"user/adv\": { \"name\": \"user/adv\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/adv\", \"via\": \"\"},
\"log/badfac\": { \"name\": \"log/badfac\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/badfac\", \"via\": \"\"},
\"loc_rc2/2.0\": { \"name\": \"loc_rc2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc2/2.0\", \"via\": \"\"},
\"system/1.0\": { \"name\": \"system/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/system/1.0\", \"via\": \"\"},
\"continue/1.0\": { \"name\": \"continue/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/1.0\", \"via\": \"\"},
\"info/type\": { \"name\": \"info/type\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/type\", \"via\": \"\"},
\"append/0.1\": { \"name\": \"append/0.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.1\", \"via\": \"\"},
\"load/00\": { \"name\": \"load/00\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/00\", \"via\": \"\"},
\"whatis/none\": { \"name\": \"whatis/none\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/none\", \"via\": \"\"},
\"append/0.2\": { \"name\": \"append/0.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.2\", \"via\": \"\"},
\"info/commandexp\": { \"name\": \"info/commandexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/commandexp\", \"via\": \"\"},
\"append/0.3\": { \"name\": \"append/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.3\", \"via\": \"\"},
\"append/0.4\": { \"name\": \"append/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.4\", \"via\": \"\"},
\"append/0.5\": { \"name\": \"append/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/0.5\", \"via\": \"\"},
\"prepend/8.0\": { \"name\": \"prepend/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/8.0\", \"via\": \"\"},
\"spread/8.0\": { \"name\": \"spread/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/8.0\", \"via\": \"\"},
\"module/relpath\": { \"name\": \"module/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/relpath\", \"via\": \"\"},
\"loc_dv2/1.0\": { \"name\": \"loc_dv2/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv2/1.0\", \"via\": \"\"},
\"spreadrc/dir7/1.0\": { \"name\": \"spreadrc/dir7/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir7/1.0\", \"via\": \"\"},
\"loc_sym/alias1\": { \"name\": \"loc_sym/alias1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias1\", \"via\": \"\"},
\"load/10\": { \"name\": \"load/10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/10\", \"via\": \"\"},
\"loc_sym/alias2\": { \"name\": \"loc_sym/alias2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias2\", \"via\": \"\"},
\"loc_rc1/1.0\": { \"name\": \"loc_rc1/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc1/1.0\", \"via\": \"\"},
\"load/11\": { \"name\": \"load/11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/11\", \"via\": \"\"},
\"conflict/relpath\": { \"name\": \"conflict/relpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/relpath\", \"via\": \"\"},
\"loc_sym/alias3\": { \"name\": \"loc_sym/alias3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias3\", \"via\": \"\"},
\"load/12\": { \"name\": \"load/12\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/12\", \"via\": \"\"},
\"loc_sym/alias4\": { \"name\": \"loc_sym/alias4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias4\", \"via\": \"\"},
\"load/13\": { \"name\": \"load/13\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/13\", \"via\": \"\"},
\"loc_sym/alias5\": { \"name\": \"loc_sym/alias5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias5\", \"via\": \"\"},
\"load/14\": { \"name\": \"load/14\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/14\", \"via\": \"\"},
\"loc_sym/alias6\": { \"name\": \"loc_sym/alias6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias6\", \"via\": \"\"},
\"load/15\": { \"name\": \"load/15\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/15\", \"via\": \"\"},
\"loc_sym/alias7\": { \"name\": \"loc_sym/alias7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias7\", \"via\": \"\"},
\"loc_sym/getvers10\": { \"name\": \"loc_sym/getvers10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/getvers10\", \"via\": \"\"},
\"load/16\": { \"name\": \"load/16\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/16\", \"via\": \"\"},
\"loc_sym/alias8\": { \"name\": \"loc_sym/alias8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias8\", \"via\": \"\"},
\"load/17\": { \"name\": \"load/17\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/17\", \"via\": \"\"},
\"modbad/info-loaded\": { \"name\": \"modbad/info-loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/info-loaded\", \"via\": \"\"},
\"loc_sym/alias9\": { \"name\": \"loc_sym/alias9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias9\", \"via\": \"\"},
\"load/18\": { \"name\": \"load/18\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/18\", \"via\": \"\"},
\"spread/5.0\": { \"name\": \"spread/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/5.0\", \"via\": \"\"},
\"load/20\": { \"name\": \"load/20\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/20\", \"via\": \"\"},
\"load/19\": { \"name\": \"load/19\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/19\", \"via\": \"\"},
\"tr2_loc/al1\": { \"name\": \"tr2_loc/al1\", \"type\": \"alias\", \"symbols\": \[ \"tr2unstable\" \], \"tags\": \[\], \"target\": \"tr_loc/trunstable\", \"via\": \"\"},
\"load/21\": { \"name\": \"load/21\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/21\", \"via\": \"\"},
\"tr2_loc/al2\": { \"name\": \"tr2_loc/al2\", \"type\": \"alias\", \"symbols\": \[ \"tr2bar\" \], \"tags\": \[\], \"target\": \"tr_loc/trbar\", \"via\": \"\"},
\"averssort/1.2.4\": { \"name\": \"averssort/1.2.4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"verssort/1.2.4\", \"via\": \"\"},
\"chdir/4.0\": { \"name\": \"chdir/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/4.0\", \"via\": \"\"},
\"load/22\": { \"name\": \"load/22\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/22\", \"via\": \"\"},
\"tr2_loc/al3\": { \"name\": \"tr2_loc/al3\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"tr2exp\", \"trreg\" \], \"tags\": \[\], \"target\": \"tr_loc/al2\", \"via\": \"\"},
\"dirmodvirt\": { \"name\": \"dirmodvirt\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"inforc/foo\": { \"name\": \"inforc/foo\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"inforc/1.0\", \"via\": \"\"},
\"load/23\": { \"name\": \"load/23\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/23\", \"via\": \"\"},
\"tr2_loc/al4\": { \"name\": \"tr2_loc/al4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"tr_loc/trexp\", \"via\": \"\"},
\"modbad/clear\": { \"name\": \"modbad/clear\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/clear\", \"via\": \"\"},
\"load/24\": { \"name\": \"load/24\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/24\", \"via\": \"\"},
\"tr2_loc/al5\": { \"name\": \"tr2_loc/al5\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"trreg\" \], \"tags\": \[\], \"target\": \"tr2_loc/tr2exp\", \"via\": \"\"},
\"load/25\": { \"name\": \"load/25\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/25\", \"via\": \"\"},
\"load/26\": { \"name\": \"load/26\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/26\", \"via\": \"\"},
\"inforc/2.0\": { \"name\": \"inforc/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"avail\", \"bar\", \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/inforc/2.0\", \"via\": \"\"},
\"load/27\": { \"name\": \"load/27\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/27\", \"via\": \"\"},
\"load/28\": { \"name\": \"load/28\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/28\", \"via\": \"\"},
\"log/err_syslog\": { \"name\": \"log/err_syslog\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_syslog\", \"via\": \"\"},
\"load/30\": { \"name\": \"load/30\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/30\", \"via\": \"\"},
\"load/29\": { \"name\": \"load/29\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/load/29\", \"via\": \"\"},
\"trace/all_on\": { \"name\": \"trace/all_on\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/trace/all_on\", \"via\": \"\"},
\"prepend/2.0\": { \"name\": \"prepend/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.0\", \"via\": \"\"},
\"loc_dv8/2.0\": { \"name\": \"loc_dv8/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv8/2.0\", \"via\": \"\"},
\"prepend/2.1\": { \"name\": \"prepend/2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.1\", \"via\": \"\"},
\"spread/2.0\": { \"name\": \"spread/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/2.0\", \"via\": \"\"},
\"prepend/2.2\": { \"name\": \"prepend/2.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.2\", \"via\": \"\"},
\"break/5.0\": { \"name\": \"break/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/5.0\", \"via\": \"\"},
\"info/isused\": { \"name\": \"info/isused\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isused\", \"via\": \"\"},
\"chdir/1.0\": { \"name\": \"chdir/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/1.0\", \"via\": \"\"},
\"prepend/2.3\": { \"name\": \"prepend/2.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.3\", \"via\": \"\"},
\"prepend/2.4\": { \"name\": \"prepend/2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/2.4\", \"via\": \"\"},
\"loc_tr\": { \"name\": \"loc_tr\", \"type\": \"directory\", \"symbols\": \[ \"reg\" \], \"via\": \"\"},
\"getenv/0.6\": { \"name\": \"getenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/getenv/0.6\", \"via\": \"\"},
\"verbose/msg\": { \"name\": \"verbose/msg\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/msg\", \"via\": \"\"},
\"spreadrc/dir4/1.0\": { \"name\": \"spreadrc/dir4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir4/1.0\", \"via\": \"\"},
\"prepend/1.10\": { \"name\": \"prepend/1.10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/1.10\", \"via\": \"\"},
\"bad2/body\": { \"name\": \"bad2/body\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad2/body\", \"via\": \"\"},
\"source/1.0\": { \"name\": \"source/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.0\", \"via\": \"\"},
\"loc_rc8/0.9\": { \"name\": \"loc_rc8/0.9\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc8/.2.0\", \"via\": \"\"},
\"source/1.1\": { \"name\": \"source/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.1\", \"via\": \"\"},
\"loc_tr/1.0\": { \"name\": \"loc_tr/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"cur\", \"stable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/1.0\", \"via\": \"\"},
\"info/mode1\": { \"name\": \"info/mode1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode1\", \"via\": \"\"},
\"source/1.2\": { \"name\": \"source/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/source/1.2\", \"via\": \"\"},
\"info/issaved\": { \"name\": \"info/issaved\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/issaved\", \"via\": \"\"},
\"info/mode2\": { \"name\": \"info/mode2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode2\", \"via\": \"\"},
\"info/mode3\": { \"name\": \"info/mode3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode3\", \"via\": \"\"},
\"module/unk\": { \"name\": \"module/unk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/unk\", \"via\": \"\"},
\"uname/unk\": { \"name\": \"uname/unk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/unk\", \"via\": \"\"},
\"info/isavail\": { \"name\": \"info/isavail\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/isavail\", \"via\": \"\"},
\"info/mode4\": { \"name\": \"info/mode4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode4\", \"via\": \"\"},
\"break/2.0\": { \"name\": \"break/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/2.0\", \"via\": \"\"},
\"loc_dv7/1.0\": { \"name\": \"loc_dv7/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv7/1.0\", \"via\": \"\"},
\"info/mode5\": { \"name\": \"info/mode5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode5\", \"via\": \"\"},
\"info/mode6\": { \"name\": \"info/mode6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/mode6\", \"via\": \"\"},
\"loc_rc6/1.2\": { \"name\": \"loc_rc6/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc6/1.2\", \"via\": \"\"},
\"tr_loc/al1\": { \"name\": \"tr_loc/al1\", \"type\": \"alias\", \"symbols\": \[ \"tr2unstable\", \"trunstable\" \], \"tags\": \[\], \"target\": \"loc_tr/next\", \"via\": \"\"},
\"versions/1.1\": { \"name\": \"versions/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.1\", \"via\": \"\"},
\"setenv/0.7.1\": { \"name\": \"setenv/0.7.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.7.1\", \"via\": \"\"},
\"tr_loc/al2\": { \"name\": \"tr_loc/al2\", \"type\": \"alias\", \"symbols\": \[ \"default\", \"tr2bar\", \"tr2exp\", \"trbar\", \"trreg\" \], \"tags\": \[\], \"target\": \"loc_tr/foo\", \"via\": \"\"},
\"loc_rcv2/2.0\": { \"name\": \"loc_rcv2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv2/.common\", \"via\": \"\"},
\"loc_rc7/1\": { \"name\": \"loc_rc7/1\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc7/1.2\", \"via\": \"\"},
\"log/err_file\": { \"name\": \"log/err_file\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_file\", \"via\": \"\"},
\"versions/1.2\": { \"name\": \"versions/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.2\", \"via\": \"\"},
\"setenv/0.7.2\": { \"name\": \"setenv/0.7.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/setenv/0.7.2\", \"via\": \"\"},
\"tr_loc/al3\": { \"name\": \"tr_loc/al3\", \"type\": \"alias\", \"symbols\": \[ \"trexp\" \], \"tags\": \[\], \"target\": \"loc_tr/al2\", \"via\": \"\"},
\"versions/1.3\": { \"name\": \"versions/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/versions/1.3\", \"via\": \"\"},
\"alias/3.0\": { \"name\": \"alias/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/alias/3.0\", \"via\": \"\"},
\"tr_loc/al4\": { \"name\": \"tr_loc/al4\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_tr/exp\", \"via\": \"\"},
\"tr_loc/al5\": { \"name\": \"tr_loc/al5\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"tr_loc/trexp\", \"via\": \"\"},
\"info/name\": { \"name\": \"info/name\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/name\", \"via\": \"\"},
\"append/7.0\": { \"name\": \"append/7.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/7.0\", \"via\": \"\"},
\"use/4.0\": { \"name\": \"use/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/4.0\", \"via\": \"\"},
\"use/4.1\": { \"name\": \"use/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/use/4.1\", \"via\": \"\"},
\"symlink2/1.0\": { \"name\": \"symlink2/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink2/1.0\", \"via\": \"\"},
\"remove/4.0\": { \"name\": \"remove/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.0\", \"via\": \"\"},
\"conflict/module\": { \"name\": \"conflict/module\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/module\", \"via\": \"\"},
\"loc_sym/alias10\": { \"name\": \"loc_sym/alias10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias10\", \"via\": \"\"},
\"remove/4.1\": { \"name\": \"remove/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.1\", \"via\": \"\"},
\"loc_sym/alias11\": { \"name\": \"loc_sym/alias11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/alias11\", \"via\": \"\"},
\"remove/4.2\": { \"name\": \"remove/4.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/4.2\", \"via\": \"\"},
\"loc_virt1/2.0\": { \"name\": \"loc_virt1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_virt1/.common\", \"via\": \"\"},
\"loc_sym/versinf1\": { \"name\": \"loc_sym/versinf1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf1\", \"via\": \"\"},
\"loc_sym/1.0\": { \"name\": \"loc_sym/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/1.0\", \"via\": \"\"},
\"loc_sym/versinf2\": { \"name\": \"loc_sym/versinf2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf2\", \"via\": \"\"},
\"loc_rc4/2.0\": { \"name\": \"loc_rc4/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc4/2.0\", \"via\": \"\"},
\"loc_sym/versinf3\": { \"name\": \"loc_sym/versinf3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf3\", \"via\": \"\"},
\"loc_sym/versinf4\": { \"name\": \"loc_sym/versinf4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf4\", \"via\": \"\"},
\"info/specified\": { \"name\": \"info/specified\", \"type\": \"modulefile\", \"symbols\": \[ \"foo\" \], \"tags\": \[\], \"pathname\": \"$modpath/info/specified\", \"via\": \"\"},
\"loc_sym/versinf5\": { \"name\": \"loc_sym/versinf5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf5\", \"via\": \"\"},
\"continue/5.0\": { \"name\": \"continue/5.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/5.0\", \"via\": \"\"},
\"loc_rcv1/1.1\": { \"name\": \"loc_rcv1/1.1\", \"type\": \"modulefile\", \"symbols\": \[ \".hidsym2\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.base\", \"via\": \"\"},
\"loc_sym/versinf6\": { \"name\": \"loc_sym/versinf6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf6\", \"via\": \"\"},
\"loc_rcv1/1.2\": { \"name\": \"loc_rcv1/1.2\", \"type\": \"modulefile\", \"symbols\": \[ \"default\", \"new\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"append/4.0\": { \"name\": \"append/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/4.0\", \"via\": \"\"},
\"loc_sym/versinf7\": { \"name\": \"loc_sym/versinf7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/versinf7\", \"via\": \"\"},
\"spreadrc/dir1/1.0\": { \"name\": \"spreadrc/dir1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir1/1.0\", \"via\": \"\"},
\"append/4.1\": { \"name\": \"append/4.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/4.1\", \"via\": \"\"},
\"use/1.0\": { \"name\": \"use/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/use/1.0\", \"via\": \"\"},
\"bad2/proc\": { \"name\": \"bad2/proc\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/bad2/proc\", \"via\": \"\"},
\"remove/1.0\": { \"name\": \"remove/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.0\", \"via\": \"\"},
\"module/err\": { \"name\": \"module/err\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/err\", \"via\": \"\"},
\"modbad/remove-path\": { \"name\": \"modbad/remove-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/remove-path\", \"via\": \"\"},
\"modbad/sh-to-mod\": { \"name\": \"modbad/sh-to-mod\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/sh-to-mod\", \"via\": \"\"},
\"modbad/edit\": { \"name\": \"modbad/edit\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/edit\", \"via\": \"\"},
\"remove/1.3\": { \"name\": \"remove/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.3\", \"via\": \"\"},
\"remove/1.4\": { \"name\": \"remove/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.4\", \"via\": \"\"},
\"uname/cache\": { \"name\": \"uname/cache\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/cache\", \"via\": \"\"},
\"loc_dv4/1.0\": { \"name\": \"loc_dv4/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv4/1.0\", \"via\": \"\"},
\"remove/1.5\": { \"name\": \"remove/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.5\", \"via\": \"\"},
\"loc_fq/1.0\": { \"name\": \"loc_fq/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_fq/1.0\", \"via\": \"\"},
\"exit/3.0\": { \"name\": \"exit/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/exit/3.0\", \"via\": \"\"},
\"remove/1.6\": { \"name\": \"remove/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.6\", \"via\": \"\"},
\"loc_rc3/1.0\": { \"name\": \"loc_rc3/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc3/1.0\", \"via\": \"\"},
\"unsetenv/0.6\": { \"name\": \"unsetenv/0.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.6\", \"via\": \"\"},
\"whatis/multiple\": { \"name\": \"whatis/multiple\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/whatis/multiple\", \"via\": \"\"},
\"remove/1.7\": { \"name\": \"remove/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.7\", \"via\": \"\"},
\"continue/2.0\": { \"name\": \"continue/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/continue/2.0\", \"via\": \"\"},
\"system/2.0\": { \"name\": \"system/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/system/2.0\", \"via\": \"\"},
\"remove/1.8\": { \"name\": \"remove/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/1.8\", \"via\": \"\"},
\"unsetenv/0.8\": { \"name\": \"unsetenv/0.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.8\", \"via\": \"\"},
\"unsetenv/0.9\": { \"name\": \"unsetenv/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/unsetenv/0.9\", \"via\": \"\"},
\"append/1.0\": { \"name\": \"append/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.0\", \"via\": \"\"},
\"append/1.1\": { \"name\": \"append/1.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.1\", \"via\": \"\"},
\"verbose/off\": { \"name\": \"verbose/off\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/off\", \"via\": \"\"},
\"append/1.3\": { \"name\": \"append/1.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.3\", \"via\": \"\"},
\"loc_def/truedef\": { \"name\": \"loc_def/truedef\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_def/truedef\", \"via\": \"\"},
\"append/1.4\": { \"name\": \"append/1.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.4\", \"via\": \"\"},
\"append/1.5\": { \"name\": \"append/1.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.5\", \"via\": \"\"},
\"module/meta\": { \"name\": \"module/meta\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/meta\", \"via\": \"\"},
\"module/empty\": { \"name\": \"module/empty\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/empty\", \"via\": \"\"},
\"append/1.6\": { \"name\": \"append/1.6\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.6\", \"via\": \"\"},
\"append/1.7\": { \"name\": \"append/1.7\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.7\", \"via\": \"\"},
\"info/shells\": { \"name\": \"info/shells\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/shells\", \"via\": \"\"},
\"append/1.8\": { \"name\": \"append/1.8\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/1.8\", \"via\": \"\"},
\"loc_dv2/2.0\": { \"name\": \"loc_dv2/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv2/2.0\", \"via\": \"\"},
\"loc_rc1/2.0\": { \"name\": \"loc_rc1/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc1/2.0\", \"via\": \"\"},
\"symlink/bar\": { \"name\": \"symlink/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"symlink/1.2\", \"via\": \"\"},
\"loc_sym/exec1\": { \"name\": \"loc_sym/exec1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec1\", \"via\": \"\"},
\"prereq/orlist\": { \"name\": \"prereq/orlist\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prereq/orlist\", \"via\": \"\"},
\"loc_sym/exec2\": { \"name\": \"loc_sym/exec2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec2\", \"via\": \"\"},
\"loc_rc7/bar\": { \"name\": \"loc_rc7/bar\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[\], \"target\": \"loc_rc7/0.9\", \"via\": \"\"},
\"loc_sym/exec3\": { \"name\": \"loc_sym/exec3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/exec3\", \"via\": \"\"},
\"modbad/empty\": { \"name\": \"modbad/empty\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/empty\", \"via\": \"\"},
\"module/lunk\": { \"name\": \"module/lunk\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lunk\", \"via\": \"\"},
\"modvar/modfile\": { \"name\": \"modvar/modfile\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modvar/modfile\", \"via\": \"\"},
\"loc_rc010/2.0\": { \"name\": \"loc_rc010/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc010/2.0\", \"via\": \"\"},
\"spread/6.0\": { \"name\": \"spread/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/6.0\", \"via\": \"\"},
\"verbose/on\": { \"name\": \"verbose/on\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verbose/on\", \"via\": \"\"},
\"loc_sym/version10\": { \"name\": \"loc_sym/version10\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version10\", \"via\": \"\"},
\"x-resource/1\": { \"name\": \"x-resource/1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/x-resource/1\", \"via\": \"\"},
\"loc_sym/version11\": { \"name\": \"loc_sym/version11\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version11\", \"via\": \"\"},
\"log/err_both_1\": { \"name\": \"log/err_both_1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_both_1\", \"via\": \"\"},
\"loc_sym/version12\": { \"name\": \"loc_sym/version12\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version12\", \"via\": \"\"},
\"loc_dv1/1.0\": { \"name\": \"loc_dv1/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv1/1.0\", \"via\": \"\"},
\"spreadrc/dir6/1.0\": { \"name\": \"spreadrc/dir6/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir6/1.0\", \"via\": \"\"},
\"loc_sym/version13\": { \"name\": \"loc_sym/version13\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version13\", \"via\": \"\"},
\"info/userexp\": { \"name\": \"info/userexp\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/info/userexp\", \"via\": \"\"},
\"log/err_both_2\": { \"name\": \"log/err_both_2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/log/err_both_2\", \"via\": \"\"},
\"modbad/is-used\": { \"name\": \"modbad/is-used\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-used\", \"via\": \"\"},
\"loc_sym/version14\": { \"name\": \"loc_sym/version14\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version14\", \"via\": \"\"},
\"loc_sym/version15\": { \"name\": \"loc_sym/version15\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version15\", \"via\": \"\"},
\"loc_sym/version16\": { \"name\": \"loc_sym/version16\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version16\", \"via\": \"\"},
\"loc_sym/version17\": { \"name\": \"loc_sym/version17\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version17\", \"via\": \"\"},
\"loc_sym/version18\": { \"name\": \"loc_sym/version18\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version18\", \"via\": \"\"},
\"recurs/modA\": { \"name\": \"recurs/modA\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/recurs/modA\", \"via\": \"\"},
\"tr2_loc\": { \"name\": \"tr2_loc\", \"type\": \"directory\", \"symbols\": \[ \"trreg\" \], \"via\": \"\"},
\"loc_sym/version19\": { \"name\": \"loc_sym/version19\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version19\", \"via\": \"\"},
\"loc_sym/version20\": { \"name\": \"loc_sym/version20\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version20\", \"via\": \"\"},
\"recurs/modB\": { \"name\": \"recurs/modB\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/recurs/modB\", \"via\": \"\"},
\"loc_dv9/1.0\": { \"name\": \"loc_dv9/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv9/1.0\", \"via\": \"\"},
\"loc_sym/version21\": { \"name\": \"loc_sym/version21\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version21\", \"via\": \"\"},
\"prepend/3.0\": { \"name\": \"prepend/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/3.0\", \"via\": \"\"},
\"getenv/1.0\": { \"name\": \"getenv/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/getenv/1.0\", \"via\": \"\"},
\"loc_sym/version22\": { \"name\": \"loc_sym/version22\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version22\", \"via\": \"\"},
\"prepend/3.1\": { \"name\": \"prepend/3.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/3.1\", \"via\": \"\"},
\"spread/3.0\": { \"name\": \"spread/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spread/3.0\", \"via\": \"\"},
\"loc_sym/version23\": { \"name\": \"loc_sym/version23\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version23\", \"via\": \"\"},
\"break/6.0\": { \"name\": \"break/6.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/6.0\", \"via\": \"\"},
\"loc_rc8/1.0\": { \"name\": \"loc_rc8/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc8/1.0\", \"via\": \"\"},
\"loc_sym/version24\": { \"name\": \"loc_sym/version24\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version24\", \"via\": \"\"},
\"chdir/2.0\": { \"name\": \"chdir/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/chdir/2.0\", \"via\": \"\"},
\"loc_sym/version25\": { \"name\": \"loc_sym/version25\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version25\", \"via\": \"\"},
\"coll/a\": { \"name\": \"coll/a\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/a\", \"via\": \"\"},
\"coll/b\": { \"name\": \"coll/b\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/b\", \"via\": \"\"},
\"loc_sym/version26\": { \"name\": \"loc_sym/version26\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_sym/version26\", \"via\": \"\"},
\"coll/c\": { \"name\": \"coll/c\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/c\", \"via\": \"\"},
\"coll/d\": { \"name\": \"coll/d\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/coll/d\", \"via\": \"\"},
\"test/1.0\": { \"name\": \"test/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/1.0\", \"via\": \"\"},
\"test/1.2\": { \"name\": \"test/1.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/test/1.2\", \"via\": \"\"},
\"user/nov\": { \"name\": \"user/nov\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/user/nov\", \"via\": \"\"},
\"conflict/fullpath\": { \"name\": \"conflict/fullpath\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/conflict/fullpath\", \"via\": \"\"},
\"loc_tr/2.0\": { \"name\": \"loc_tr/2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"next\", \"tr2unstable\", \"trunstable\", \"unstable\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_tr/2.0\", \"via\": \"\"},
\"module/lerr\": { \"name\": \"module/lerr\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/lerr\", \"via\": \"\"},
\"uname/version\": { \"name\": \"uname/version\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/uname/version\", \"via\": \"\"},
\"remove/8.0\": { \"name\": \"remove/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/remove/8.0\", \"via\": \"\"},
\"prepend/0.1\": { \"name\": \"prepend/0.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.1\", \"via\": \"\"},
\"loc_dv7/2.0\": { \"name\": \"loc_dv7/2.0\", \"type\": \"directory\", \"symbols\": \[ \"default\" \], \"via\": \"\"},
\"module/.ignored\": { \"name\": \"module/.ignored\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/module/.ignored\", \"via\": \"\"},
\"module/2.0\": { \"name\": \"module/2.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/module/2.0\", \"via\": \"\"},
\"prepend/0.2\": { \"name\": \"prepend/0.2\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.2\", \"via\": \"\"},
\"break/3.0\": { \"name\": \"break/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/break/3.0\", \"via\": \"\"},
\"modbad/prepend-path\": { \"name\": \"modbad/prepend-path\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/prepend-path\", \"via\": \"\"},
\"prepend/0.3\": { \"name\": \"prepend/0.3\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.3\", \"via\": \"\"},
\"dirmodalias/1.0\": { \"name\": \"dirmodalias/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/dirmodalias/1.0\", \"via\": \"\"},
\"prepend/0.4\": { \"name\": \"prepend/0.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.4\", \"via\": \"\"},
\"verssort/1.2.1\": { \"name\": \"verssort/1.2.1\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.2.1\", \"via\": \"\"},
\"modbad/is-loaded\": { \"name\": \"modbad/is-loaded\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/modbad/is-loaded\", \"via\": \"\"},
\"prepend/0.5\": { \"name\": \"prepend/0.5\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/prepend/0.5\", \"via\": \"\"},
\"verssort/1.2.4\": { \"name\": \"verssort/1.2.4\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/verssort/1.2.4\", \"via\": \"\"},
\"loc_dv6/2.0/1.0\": { \"name\": \"loc_dv6/2.0/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_dv6/2.0/1.0\", \"via\": \"\"},
\"spreadrc/dir3/1.0\": { \"name\": \"spreadrc/dir3/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/spreadrc/dir3/1.0\", \"via\": \"\"},
\"loc_dvv1/1.0\": { \"name\": \"loc_dvv1/1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[\], \"pathname\": \"$modpath/loc_dvv1/.common\", \"via\": \"\"},
\"append/8.0\": { \"name\": \"append/8.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/append/8.0\", \"via\": \"\"},
\"symlink/0.9\": { \"name\": \"symlink/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/symlink/0.9\", \"via\": \"\"},
\"loc_sym/.common\": { \"name\": \"loc_sym/.common\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_sym/.common\", \"via\": \"\"},
\"loc_rcv2/.common\": { \"name\": \"loc_rcv2/.common\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rcv2/.common\", \"via\": \"\"},
\"loc_rcv1/.base\": { \"name\": \"loc_rcv1/.base\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rcv1/.base\", \"via\": \"\"},
\"loc_rcv1/.common\": { \"name\": \"loc_rcv1/.common\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rcv1/.common\", \"via\": \"\"},
\"loc_rcv1/.hidvirt\": { \"name\": \"loc_rcv1/.hidvirt\", \"type\": \"modulefile\", \"symbols\": \[ \".hidsym\" \], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rcv1/.base\", \"via\": \"\"},
\"loc_rc8/.2.0\": { \"name\": \"loc_rc8/.2.0\", \"type\": \"modulefile\", \"symbols\": \[ \"foo\" \], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc8/.2.0\", \"via\": \"\"},
\"loc_rc9/.1.0\": { \"name\": \"loc_rc9/.1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc9/.1.0\", \"via\": \"\"},
\"loc_rc010/.1.0\": { \"name\": \"loc_rc010/.1.0\", \"type\": \"modulefile\", \"symbols\": \[ \"default\" \], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc010/.1.0\", \"via\": \"\"},
\"loc_rc010/.2.2\": { \"name\": \"loc_rc010/.2.2\", \"type\": \"alias\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"target\": \"loc_rc010/2.0\", \"via\": \"\"},
\"loc_rc010/dir/.4.0\": { \"name\": \"loc_rc010/dir/.4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc010/dir/.4.0\", \"via\": \"\"},
\"loc_rc010/subdir/.hidsub/3.0\": { \"name\": \"loc_rc010/subdir/.hidsub/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc010/subdir/.hidsub/3.0\", \"via\": \"\"},
\"loc_rc010/subdir/.subdir\": { \"name\": \"loc_rc010/subdir/.subdir\", \"type\": \"directory\", \"symbols\": \[ \"default\" \], \"via\": \"\"},
\"loc_rc010/subdir/.subdir/3.0\": { \"name\": \"loc_rc010/subdir/.subdir/3.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc010/subdir/.subdir/3.0\", \"via\": \"\"},
\"loc_rc8/.subdir/4.0\": { \"name\": \"loc_rc8/.subdir/4.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_rc8/.subdir/4.0\", \"via\": \"\"},
\"loc_rc010/dir\": { \"name\": \"loc_rc010/dir\", \"type\": \"directory\", \"symbols\": \[ \"foo\" \], \"via\": \"\"},
\"loc_dvv1/.common\": { \"name\": \"loc_dvv1/.common\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/loc_dvv1/.common\", \"via\": \"\"},
\".hidden/1.0\": { \"name\": \".hidden/1.0\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[ \"hidden\" \], \"pathname\": \"$modpath/.hidden/1.0\", \"via\": \"\"},
\"loc_rc7/0.9\": { \"name\": \"loc_rc7/0.9\", \"type\": \"modulefile\", \"symbols\": \[\], \"tags\": \[\], \"pathname\": \"$modpath/loc_rc7/0.9\", \"via\": \"\"}
}}"

set ts_sh_small "- $modpath.deep -
badmodvers/dir1/2.0                                   
badmodvers/foo                                        
dir2/1.0(d1)                                          
dir2/3.0(d3)                                          
modalias/1.0(@)                                       
modalias/3.0                                          
modalias/dir1/1.0                                     
modalias/dir1/2.0(@)                                  
modalias/dir2/2.0                                     
modalias/dir2/3.0(@)                                  
moddalias(@)                                          
moddalias/dir1/1                                      
moddef/dir2/1.0(default)                              
moddef/dir2/2.0                                       
modload/dir2/1.0(md1)                                 
modload/dir2/3.0(md3)                                 
modsym/dir1/1.0(3.0)                                  
modsym/dir2/2.0(3.0)                                  
modtr/3.0(bar:exp:foo:reg:tr2bar:trbar)               
modtr/al1(unstable:@)                                 
modtr/al4(default:reg:@)                              
modtr/al5(fld:@)                                      
modtr/al6(sfld:@)                                     
modtr/dir1/1.0(cur:stable)                            
modtr/dir2/2.0(next:tr2unstable:trunstable:unstable)  
modtr/dir3/al2(bar:default:exp:reg:tr2bar:trbar:@)    
modtr/dir3/al3(default:exp:reg:@)                     
modtr/dir4/(default:fld:reg:trfld:trreg)              
modtr/dir4/al7(madj:@)                                
modtr/dir4/al8(dadj:@)                                
modtr/dir4/mod4.0                                     
modtr/dir5/subdir/(dadj:sfld)                         
modtr/dir5/subdir/mod5.0(madj)                        
modulerc/dir1/(default)                               
modulerc/dir1/1.0(default)                            
modulerc/dir1/2.0                                     
modulerc/dir2/(foo)                                   
modulerc/dir2/1.0/(default:foo)                       
modulerc/dir2/1.0/rc1(default:foo)                    
modulerc/dir2/1.0/rc2                                 
modulerc/dir2/2.0                                     
modulerc/dir2/3.0                                     
modvirt/1.0(@)                                        
modvirt/3.0                                           
modvirt/dir0/sub1/4.0                                 
modvirt/dir0/sub1/5.0(@)                              
modvirt/dir0/sub1/6.0                                 
modvirt/dir1/1.0                                      
modvirt/dir1/2.0(@)                                   
modvirt/dir2/2.0                                      
modvirt/dir2/3.0(@)                                   
plain/dir1/1.0                                        
plain/dir1/2.0                                        
plain/dir2/1.0                                        
plain/dir2/2.0                                        
tr2mod/al1(tr2unstable:@)                             
tr2mod/al5(tr2fld:@)                                  
tr2mod/dir3/al2(tr2bar:@)                             
trmod/(trreg)                                         
trmod/al1(tr2unstable:trunstable:@)                   
trmod/al5(default:trfld:trreg:@)                      
trmod/dir3/(tr2fld)                                   
trmod/dir3/al2(tr2bar:trbar:@)                        
version/dir1/(default)                                
version/dir1/1.0(default)                             
version/dir1/2.0                                      
version/dir2/1.0                                      
version/dir2/2.0/(default)                            
version/dir2/2.0/rc1(default)                         
version/dir2/2.0/rc2                                  
version/dir2/3.0                                      "

set len  [string length $modpath.deep]
set lrep [expr {($test_cols_othos - $len - 2)/2}]
set rrep [expr {$test_cols_othos - $len - 2 - $lrep}]
set ts_sh_noflag_othos "[string repeat {-} $lrep] $modpath.deep [string repeat {-} $rrep]
badmodvers/dir1/2.0  modload/dir2/3.0  modtr/dir4/mod4.0         modvirt/dir0/sub1/5.0  trmod/al5             
badmodvers/foo       modsym/dir1/1.0   modtr/dir5/subdir/        modvirt/dir0/sub1/6.0  trmod/dir3/           
dir2/1.0             modsym/dir2/2.0   modtr/dir5/subdir/mod5.0  modvirt/dir1/1.0       trmod/dir3/al2        
dir2/3.0             modtr/3.0         modulerc/dir1/            modvirt/dir1/2.0       version/dir1/         
modalias/1.0         modtr/al1         modulerc/dir1/1.0         modvirt/dir2/2.0       version/dir1/1.0      
modalias/3.0         modtr/al4         modulerc/dir1/2.0         modvirt/dir2/3.0       version/dir1/2.0      
modalias/dir1/1.0    modtr/al5         modulerc/dir2/            plain/dir1/1.0         version/dir2/1.0      
modalias/dir1/2.0    modtr/al6         modulerc/dir2/1.0/        plain/dir1/2.0         version/dir2/2.0/     
modalias/dir2/2.0    modtr/dir1/1.0    modulerc/dir2/1.0/rc1     plain/dir2/1.0         version/dir2/2.0/rc1  
modalias/dir2/3.0    modtr/dir2/2.0    modulerc/dir2/1.0/rc2     plain/dir2/2.0         version/dir2/2.0/rc2  
moddalias            modtr/dir3/al2    modulerc/dir2/2.0         tr2mod/al1             version/dir2/3.0      
moddalias/dir1/1     modtr/dir3/al3    modulerc/dir2/3.0         tr2mod/al5             
moddef/dir2/1.0      modtr/dir4/       modvirt/1.0               tr2mod/dir3/al2        
moddef/dir2/2.0      modtr/dir4/al7    modvirt/3.0               trmod/                 
modload/dir2/1.0     modtr/dir4/al8    modvirt/dir0/sub1/4.0     trmod/al1              "

#
#  test
#

testouterr_cmd "sh" "avail" "OK" "$ts_sh\n\n$ts_key"

# test JSON output over a global result
testouterrjson_cmd sh {avail --json} OK $ts_sh_json
testouterrjson_cmd sh {avail --all --json} OK $ts_sh_all_json

if {[is_quick_mode]} {
    exec stty cols $term_cols
}
skip_if_quick_mode

# setup MODULEPATH with a trailing slash and an empty dir element
setenv_path_var MODULEPATH {} "$modpath/"
testouterr_cmd "sh" "avail" "OK" "$ts_sh\n\n$ts_key"


# test with a small terminal width
exec stty cols $test_cols_small
setenv_path_var MODULEPATH "$modpath.deep"
testouterr_cmd "sh" "avail" "OK" "$ts_sh_small\n\n$ts_key_small"


# check excepted siteconfig file is installed
if {[siteconfig_isStderrTty]} {

# simulate Solaris OS with its specific stty command output
if {$verbose} {
    send_user "\tSetup TESTSUITE_ENABLE_SITECONFIG_SOLARIS_STTY = '1'\n"
}
set env(TESTSUITE_ENABLE_SITECONFIG_SOLARIS_STTY) 1

testouterr_cmd "sh" "avail -o alias:modulepath:dirwsym" "OK" "$ts_sh_noflag_othos"


# simulate Windows OS with its specific mode command output
if {$verbose} {
    send_user "\tSetup TESTSUITE_ENABLE_SITECONFIG_WINDOWS_MODE = '1'\n"
}
set env(TESTSUITE_ENABLE_SITECONFIG_WINDOWS_MODE) 1

testouterr_cmd "sh" "avail -o alias:modulepath:dirwsym" "OK" "$ts_sh_noflag_othos"

# restore environment
if {$verbose} {
    send_user "\tUnset TESTSUITE_ENABLE_SITECONFIG_SOLARIS_STTY\n"
    send_user "\tUnset TESTSUITE_ENABLE_SITECONFIG_WINDOWS_MODE\n"
}
unset env(TESTSUITE_ENABLE_SITECONFIG_SOLARIS_STTY)
unset env(TESTSUITE_ENABLE_SITECONFIG_WINDOWS_MODE)

} elseif {$verbose} {
   send_user "\tSkip some tests as excepted siteconfig file not installed\n"
}


#
#  Cleanup
#

# restore terminal width
exec stty cols $term_cols

}

reset_test_env
