##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.50-cmds/%M%
#   Revision:		%I%
#   First Edition:	2023/07/07
#   Last Mod.:		%U%, %G%
#
#   Authors:		Xavier Delaruelle, xavier.delaruelle@cea.fr
#
#   Description:	Testuite testsequence
#   Command:		purge, unload
#   Modulefiles:
#   Sub-Command:
#
#   Comment:	%C{
#           Check sticky_purge configuration option
#		}C%
#
##############################################################################

set mp $modpath.4
set mpre $modpathre.4
setenv_path_var MODULEPATH $mp


#
# purge
#

# sticky module
setenv_var TESTSUITE_FPMOD_TAG sticky1
setenv_loaded_module [list tag/1.0 foo/1.0] [list $mp/tag/1.0 $mp/foo/1.0]
setenv_var __MODULES_LMTAG tag/1.0&sticky

setenv_var MODULES_STICKY_PURGE error
set ans [list]
lappend ans [list set LOADEDMODULES tag/1.0]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list ERR]
set tserr [msg_unload {tag/1.0 <S>} $err_stickyunload]
testouterr_cmd sh {purge} $ans $tserr

setenv_var MODULES_STICKY_PURGE warning
set ans [list]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list set LOADEDMODULES tag/1.0]
set tserr [msg_unload {tag/1.0 <S>} $warn_stickyunload]
testouterr_cmd sh {purge} $ans $tserr

setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {purge} $ans {}

skip_if_quick_mode

# forced purge
setenv_var MODULES_STICKY_PURGE error
set ans [list]
lappend ans [list unset _LMFILES_]
lappend ans [list unset LOADEDMODULES]
lappend ans [list unset __MODULES_LMTAG]
set tserr [msg_unload {tag/1.0 <S>} $err_stickyunloadf]
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE warning
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {purge -f} $ans $tserr


# super-sticky module
setenv_var TESTSUITE_FPMOD_TAG sticky2
setenv_loaded_module [list foo/1.0 tag/1.0] [list $mp/foo/1.0 $mp/tag/1.0]
setenv_var __MODULES_LMTAG tag/1.0&super-sticky

setenv_var MODULES_STICKY_PURGE error
set ans [list]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list set LOADEDMODULES tag/1.0]
lappend ans [list ERR]
set tserr [msg_unload {tag/1.0 <sS>} $err_superstickyunload]
testouterr_cmd sh {purge} $ans $tserr
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE warning
set ans [list]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list set LOADEDMODULES tag/1.0]
set tserr [msg_unload {tag/1.0 <sS>} $warn_superstickyunload]
testouterr_cmd sh {purge} $ans $tserr
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {purge} $ans {}
testouterr_cmd sh {purge -f} $ans {}


# super-sticky module with non-sticky requirement
setenv_var TESTSUITE_STICKY purge_req
setenv_loaded_module [list sticky1/1.0 sticky2/1.0] [list\
    $mp/sticky1/1.0 $mp/sticky2/1.0]
setenv_var __MODULES_LMTAG sticky2/1.0&super-sticky
setenv_var __MODULES_LMPREREQ sticky2/1.0&sticky1/1.0|sticky1/2.0

set ans [list]

setenv_var MODULES_STICKY_PURGE error
set anserr $ans
lappend anserr [list ERR]
set tserr [msg_unload {sticky2/1.0 <sS>}\
    $err_superstickyunload]\n\n[msg_unload sticky1/1.0\
    $err_superstickyrequnload]
testouterr_cmd sh {purge} $anserr $tserr
testouterr_cmd sh {purge -f} $anserr $tserr

setenv_var MODULES_STICKY_PURGE warning
set tserr [msg_unload {sticky2/1.0 <sS>}\
    $warn_superstickyunload]\n\n[msg_unload sticky1/1.0\
    $warn_superstickyrequnload]
testouterr_cmd sh {purge} $ans $tserr
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {purge} $ans {}
testouterr_cmd sh {purge -f} $ans {}

unsetenv_var TESTSUITE_STICKY


# sticky module with non-sticky requirement, including forced unload
setenv_var __MODULES_LMTAG sticky2/1.0&sticky
foreach {report_mode msg reqmsg} [list error $err_stickyunload\
    $err_stickyrequnload warning $warn_stickyunload\
    $warn_stickyrequnload silent {} {}] {
    setenv_var MODULES_STICKY_PURGE $report_mode
    set ans [list]
    if {$report_mode eq {error}} {
        lappend ans [list ERR]
    }
    set tserr {}
    if {$report_mode ne {silent}} {
        set tserr [msg_unload {sticky2/1.0 <S>} $msg]\n\n[msg_unload\
            sticky1/1.0 $reqmsg]
    }
    testouterr_cmd sh {purge} $ans $tserr

    set ans [list]
    foreach var {__MODULES_LMPREREQ _LMFILES_ LOADEDMODULES __MODULES_LMTAG} {
        lappend ans [list unset $var]
    }
    set tserr [msg_unload {sticky2/1.0 <S>} $err_stickyunloadf]
    testouterr_cmd sh {purge -f} $ans $tserr
}


# registered dependency chain: sticky3 -> sticky2 -> sticky1
setenv_loaded_module [list sticky1/1.0 sticky2/1.0 sticky3/1.0] [list\
    $mp/sticky1/1.0 $mp/sticky2/1.0 $mp/sticky3/1.0]
setenv_var __MODULES_LMTAG sticky3/1.0&super-sticky
setenv_var __MODULES_LMPREREQ\
    sticky2/1.0&sticky1/1.0|sticky1/2.0:sticky3/1.0&sticky2/1.0
foreach auto_handling {0 1} {
    setenv_var MODULES_AUTO_HANDLING $auto_handling
    foreach {report_mode msg reqmsg} [list error $err_superstickyunload\
        $err_superstickyrequnload warning $warn_superstickyunload\
        $warn_superstickyrequnload silent {} {}] {
        setenv_var MODULES_STICKY_PURGE $report_mode
        set ans [list]
        if {$report_mode eq {error}} {
            lappend ans [list ERR]
        }
        set tserr {}
        if {$report_mode ne {silent}} {
            set tserr [msg_unload {sticky3/1.0 <sS>} $msg]\n\n[msg_unload\
                sticky2/1.0 $reqmsg]\n\n[msg_unload sticky1/1.0 $reqmsg]
        }
        testouterr_cmd sh {purge} $ans $tserr
        testouterr_cmd sh {purge -f} $ans $tserr
    }
}
unsetenv_var MODULES_AUTO_HANDLING


# unload an alternative requirement while retaining the last necessary one
setenv_var TESTSUITE_STICKY purge_req
setenv_loaded_module [list sticky1/1.0 sticky1/2.0 sticky2/1.0] [list\
    $mp/sticky1/1.0 $mp/sticky1/2.0 $mp/sticky2/1.0]
setenv_var __MODULES_LMTAG sticky2/1.0&super-sticky
setenv_var __MODULES_LMPREREQ sticky2/1.0&sticky1/1.0|sticky1/2.0
setenv_var MODULES_STICKY_PURGE silent
set ans [list]
lappend ans [list set _LMFILES_ $mp/sticky1/1.0:$mp/sticky2/1.0]
lappend ans [list set LOADEDMODULES sticky1/1.0:sticky2/1.0]
testouterr_cmd sh {purge} $ans {}
testouterr_cmd sh {purge -f} $ans {}
unsetenv_var TESTSUITE_STICKY


# super-sticky takes precedence regardless of dependent load order
setenv_loaded_module [list sticky1/1.0 sticky2/1.0 sticky3/1.0] [list\
    $mp/sticky1/1.0 $mp/sticky2/1.0 $mp/sticky3/1.0]
setenv_var __MODULES_LMPREREQ\
    sticky2/1.0&sticky1/1.0:sticky3/1.0&sticky1/1.0
setenv_var MODULES_STICKY_PURGE warning
foreach {tag2 tag3 msg2 msg3} [list sticky super-sticky\
    $warn_stickyunload $warn_superstickyunload super-sticky sticky\
    $warn_superstickyunload $warn_stickyunload] {
    setenv_var __MODULES_LMTAG sticky2/1.0&$tag2:sticky3/1.0&$tag3
    set abbrev2 [expr {$tag2 eq {sticky} ? {S} : {sS}}]
    set abbrev3 [expr {$tag3 eq {sticky} ? {S} : {sS}}]
    set tserr [msg_unload "sticky3/1.0 <$abbrev3>" $msg3]\n\n[msg_unload\
        "sticky2/1.0 <$abbrev2>" $msg2]\n\n[msg_unload sticky1/1.0\
        $warn_superstickyrequnload]
    testouterr_cmd sh {purge} {} $tserr
}
unsetenv_var __MODULES_LMPREREQ


# module both sticky and super-sticky
setenv_var TESTSUITE_FPMOD_TAG sticky2
setenv_loaded_module [list foo/1.0 tag/1.0] [list $mp/foo/1.0 $mp/tag/1.0]
setenv_var __MODULES_LMTAG tag/1.0&super-sticky&sticky

setenv_var MODULES_STICKY_PURGE error
set ans [list]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list set LOADEDMODULES tag/1.0]
lappend ans [list ERR]
set tserr [msg_unload {tag/1.0 <S:sS>} $err_superstickyunload]
testouterr_cmd sh {purge} $ans $tserr
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE warning
set ans [list]
lappend ans [list set _LMFILES_ $mp/tag/1.0]
lappend ans [list set LOADEDMODULES tag/1.0]
set tserr [msg_unload {tag/1.0 <S:sS>} $warn_superstickyunload]
testouterr_cmd sh {purge} $ans $tserr
testouterr_cmd sh {purge -f} $ans $tserr

setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {purge} $ans {}
testouterr_cmd sh {purge -f} $ans {}


#
# unload (configuration has no effect)
#

setenv_var TESTSUITE_FPMOD_TAG sticky1
setenv_loaded_module [list tag/1.0 foo/1.0] [list $mp/tag/1.0 $mp/foo/1.0]
setenv_var __MODULES_LMTAG tag/1.0&sticky

setenv_var MODULES_STICKY_PURGE error
set tserr [msg_unload {tag/1.0 <S>} $err_stickyunload]
testouterr_cmd sh {unload tag/1.0} ERR $tserr
setenv_var MODULES_STICKY_PURGE warning
testouterr_cmd sh {unload tag/1.0} ERR $tserr
setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {unload tag/1.0} ERR $tserr


setenv_var TESTSUITE_FPMOD_TAG sticky2
setenv_var __MODULES_LMTAG tag/1.0&super-sticky

setenv_var MODULES_STICKY_PURGE error
set tserr [msg_unload {tag/1.0 <sS>} $err_superstickyunload]
testouterr_cmd sh {unload tag/1.0} ERR $tserr
setenv_var MODULES_STICKY_PURGE warning
testouterr_cmd sh {unload tag/1.0} ERR $tserr
setenv_var MODULES_STICKY_PURGE silent
testouterr_cmd sh {unload tag/1.0} ERR $tserr


#
#  Cleanup
#

reset_test_env
